### ISSUE TITLE
Notepad++ not saving the file with extension

### ISSUE THREAD

**Issue by modulexcite** [notepad-plus-plus/notepad-plus-plus#1129]
Hi,

Notepad++ is not saving the files with an extension; it doesn't matter what language I choose it's not saving the file with an extension. They are just saved with the file names without any extension. I've tried to revert to the 6.8.5 version from 6.8.6 but the problem persists.
When I press "Ctrl+S" or select the option from the File Toolbar option; the "Save as type" option always defaults to "All types(*.*)" and the file is saved without an extension even if I type the extension ".txt" or something else in the file name.
Please advise on how to get this resolved.

Thanks

**Comment by modulexcite** [comment]
![2015-11-11_11-54-47](https://cloud.githubusercontent.com/assets/12729391/11097068/329aa882-886b-11e5-9b12-bae2ad6c96c7.gif)

Attached is a screen capture of the above issue if it helps

**Comment by mohamedahmedabdelfattah** [comment]
Just landed here to report this bug so i`m confirming it

**Comment by kikex76** [comment]
+1. I tried 3 different computers, 2 physical 1 vmware running with Windows 7. I performed clean installs and everything with no luck. I then reverted back to Notepadd++ version 6.8.3, and works fine again.

**Comment by mohamedahmedabdelfattah** [comment]
yeah, after investigating this problem started from 6.8.4 final release

**Comment by modulexcite** [comment]
Yes it has started from version 6.8.4 so I had to revert to 6.8.3 and I intend to keep it that way unless they fix this in the new version, I think one of the authors has mentioned about this change in a similar issue reported earlier but I prefer the old way of not having to enter the extension after selecting the language of the file.

___________________________
Thanks.




On Sat, Nov 14, 2015 at 7:42 AM -0800, "Mohamed Ahmed Abdel Fattah" <notifications@github.com> wrote:












yeah, after investigating this problem started from 6.8.4 final release

**Comment by mohamedahmedabdelfattah** [comment]
it appears to be something with commit #d738f80

**Comment by bean-drew** [comment]
Chiming in to voice dismay about and interest in a fix for the present state of saving with(out) file extensions in 6.8.4-6.

**Comment by BASIQ** [comment]
Here to post my disappointment with this change as well. Please fix this, Sometime I wonder if you guys actually use the software you make, how can something so big as this fly under the radar?

**Comment by mtRoom** [comment]
Please fix this if possible. In all the years of using NPP, this is the first issue I've had.

**Comment by mohamedahmedabdelfattah** [comment]
already fixed in v6.8.7 and above

**Comment by mtRoom** [comment]
Okay thanks. Strange. I'm running 6.8.6 and clicked 'Update Notepad++' and it said no updates found.

**Comment by mohamedahmedabdelfattah** [comment]
weird, try manual update to get the fix and investigate more if you can and we are here to help

**Comment by modulexcite** [comment]
I just installed 6.8.8 but the issue persists, are you sure this has been fixed?

___________________________
Thanks.




On Fri, Dec 18, 2015 at 8:36 PM -0800, "Mohamed Ahmed Abdel Fattah" <notifications@github.com> wrote:












weird, try manual update to get the fix and investigate more if you can and we are here to help

**Comment by modulexcite** [comment]
Not sure if this matters I didn't uninstall the old version I was using 6.8.3 as I wanted to give the new version a try before uninstalling it. So I used the portable 6.8.8 to test this issue and it's still not saving the files with an extension.

___________________________
Thanks.




On Fri, Dec 18, 2015 at 8:36 PM -0800, "Mohamed Ahmed Abdel Fattah" <notifications@github.com> wrote:












weird, try manual update to get the fix and investigate more if you can and we are here to help

**Comment by mtRoom** [comment]
It's working for me now with 6.8.8. I just installed it over the top of the portable one, no problems.

**Comment by mohamedahmedabdelfattah** [comment]
@modulexcite yes i`m sure and mrRoom confirmed that but i i don`t know what to say, isn`t the portable versions fully in-dependable from the system and the installed version
