### ISSUE TITLE
[Feature request] Limit scope of 'Search results' right-click 'Open all' and 'Copy Pathname(s)' commands

### ISSUE THREAD

**Issue by alankilborn** [notepad-plus-plus/notepad-plus-plus#15741]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

Scenario:  User has run many file-level searches in his Notepad++ working period, a lot of which are no longer relevant to what he is currently doing.  His _Search results_ panel is populated with much data, but he doesn't want to clear it.  He runs a new search and from this he wants to open all of the files with hits from _only_ that search.  He has no way to achieve this as the right-click command _Open all_ will, as it implies, open _all_ files in _all_ previous file-level searches ever conducted.

### Describe the solution you'd like.

User should be able to command that only file(s) from a specific previous search be opened.  The user would right-click on a "top-level" line from a prior search, i.e., the line that begins with `Search "..."`, choose e.g. _Open selected_ (the text of which would replace the current _Open all_), and then only the files with hits from that search would be opened into Notepad++.

If the user wanted the current (8.7) behavior, he could Ctrl+a (select-all) in _Search results_ before right-clicking and choosing _Open selected_.

---

Notes:

* The description discusses opening files, but a similar concept can be applied to _Copy Pathname(s)_ -- menu text on this one would change to _Copy Selected Pathname(s)_
* The overall logistical operation would be very similar to how _Copy Selected Line(s)_ currently works, see [UM](https://npp-user-manual.org/docs/searching/#kbdrightclickkbd-commands-in-the-client-area-of-a-search-results-windows-tab) for that behavior

### Debug Information

```shell
Notepad++ v8.7   (64-bit)
Build time : Sep 17 2024 - 17:06:31
Path : C:\NotepadPlusPlus\Misc\_NoBackup\Releases\npp.8.7\npp.8.7.portable.x64\notepad++.exe
Command Line : -titleAdd="8.7 64-bit" -multiInst
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
Periodic Backup : ON
OS Name : Windows 11 Pro (64-bit)
OS Version : 23H2
OS Build : 22631.4317
Current ANSI codepage : 1252
Plugins : 
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)
    PythonScript (2)
```

**Comment by alankilborn** [comment]
@donho Do you like this idea? If so, please assign me.

Note: Changes are small; almost exclusively changes in one function:  `Finder::getResultFilePaths()`

**Comment by donho** [comment]
@alankilborn 
Sorry, I don't follow at all the description of the feature you want.
Maybe the screenshots could help me understand your need better.

**Comment by alankilborn** [comment]
A concrete example to help clarify:

I've run many searches as I've worked with Notepad++ for several hours today:

![image](https://github.com/user-attachments/assets/25af4840-8ffb-4c57-bd40-22040e4a3b4a)

I decide that I now need to open the files from my prior search for `z`:

![image](https://github.com/user-attachments/assets/73454d1a-7fcd-481a-baba-2af4e6e9a418)

If I select the lines of the files I need to open, right-click and choose _Open all_:

![image](https://github.com/user-attachments/assets/07f08c85-dbf0-45eb-8c4f-4d6780d5664c)

instead of at most 8 files opening into new tabs (my desire from the selection I made), I get -- for my case, due to my prior other searches -- 98 files opening into new tabs!

It would be nice if opening (or copying pathnames from) files via the _Search results_ right-click command could be limited to the files of _selected_ text, and not simply _all_ prior search text.

**Comment by xomx** [comment]
@alankilborn 


> If the user wanted the current (8.7) behavior, he could Ctrl+a (select-all) in _Search results_ before right-clicking and choosing _Open selected_.

And if nothing is selected at all - would you also keep the current behavior (open all the files) or not?

**Comment by alankilborn** [comment]
>And if nothing is selected at all - would you also keep the current behavior (open all the files) or not?

I personally would not retain that behavior.
Ideally (after some evolved thinking from initially writing this feature request issue), I would like to see "Open all" changed to "Open Selected Pathname(s)".  Then it is clearer to the user what the command does and what preconditions are necessary (selecting something).  In the very-rare¹ instance the user did indeed want ALL files to open from ALL prior searches, a quick Ctrl+a could be done before the command is executed.

The same holds true for copying paths; I would change the existing "Copy Pathname(s)" to "Copy Selected Pathname(s)".

¹: very-rare _usually_, although I understand that it could be less rare if user has this setting:
![image](https://github.com/user-attachments/assets/272403ee-0e19-4b5b-a779-ec09195cd6ff)

**Comment by softmgr** [comment]
The code in the **getResultFilePaths** function:
```
auto endIndex = lineStr.find_last_of(L'(');
```
This implementation has a problem because in the **getHitsString** function, the left parenthesis character L'(' is included in the localized resource string:
```
wstring text = pNativeSpeaker->getLocalizedStrFromID("find-result-hits", L"");
```
However, the translation varies for each country, and it might be a different character. The **"find-result-hits"** resource string may not even contain a parenthesis character at all.

**Comment by donho** [comment]
@softmgr 
Indeed, "find-result-hits" could contain any translation and not necessary`(` & `)`.

@alankilborn 
Could you use the original algorithm for a new PR for fixing this eventual bug?

**Comment by alankilborn** [comment]
Yes, I'll take a look at it.
It may be that the translation could be structured better.

**Comment by softmgr** [comment]
> Yes, I'll take a look at it. It may be that the translation could be structured better.

I rewrote the following code based on the previous version, and it is not related to localized resource strings. This is for reference only.


```

	size_t len = _pMainFoundInfos->size();  // First, get the number of elements in the container
	for (size_t line = fromLine; line <= toLine; ++line)
	{
		bool found = false;  // Was it found?
		const int lineFoldLevel = _scintView.execute(SCI_GETFOLDLEVEL, line) & SC_FOLDLEVELNUMBERMASK;
		if (lineFoldLevel == fileHeaderLevel)
		{
			line++;  // Move to the next line
			if (line < len)
				found = true;  // Found it
		}
		else if (lineFoldLevel == resultLevel)
		{
			if (line < len)
				found = true;  // Found it
		}
		if (found)
		{
			wstring& path = (*_pMainFoundInfos)[line]._fullPath;  // Get the path from the container
			if (path.find('\\') != std::wstring::npos && std::find(paths.begin(), paths.end(), path) == paths.end())  // Contains a path separator and does not exist in the container
			{
				paths.push_back(path);
			}
		}
	}

```

**Comment by donho** [comment]
@softmgr 
Tested, it fixed the bug.
Could you create a PR please?

**Comment by alankilborn** [comment]
@softmgr won't do PRs, despite the fact that I have requested that he do so where he has posted code in other issue comments.

@donho I'm surprised you tested this code.

---

I would not fix it that way.

As I said above, the way the translation is handled for this is designed poorly, IMO.
All that needs to be translated is the word `hits`.
There is no reason for the translation string to include `(`, the number of hits, and `)`.
(Silly question: so why isn't the translation string also required to include the space before the `(` ?)
The current design was probably done because it was "easy"?
BUT...we won't redesign that here... it's been entrenched for so long now...

Since it is long established convention now that these type of lines appear as:
`  C:\folder\file.ext (N hits)`
I would suggest fixing it by _requiring_ that the translation text begin with `(` and contain no additional `(`.
That way, `find_last_of` will always find a `(` and it will be the correct `(`.
Thus, change [THIS](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/eeb47530449cebabc9c94a8bccefc0f574a2491c/PowerEditor/src/ScintillaComponent/FindReplaceDlg.cpp#L5142) line to be:

`if (text.empty() || text[0] != L'(' || std::ranges::count(text, L'(') != 1)`

This way, if a translator doesn't follow that requirement, their text won't be translated (and it will serve to remind them to do it correctly; an appropriate comment can be put in english.xml about it).

**Comment by donho** [comment]
>  I'm surprised you tested this code.

How come?

> As I said above, the way the translation is handled for this is designed poorly, IMO.

It's debatable. From the view of the translation, it makes sense to me.

The symbols with the same meaning has the different representation in the different languages.
For example, **`"XXX"`** translated in Mandarin should be **`「YYY」`**.

For the parenthesis in Mandarin, there's less visual difference, but still for non-Mandarin native people, they can tell the difference when they look closely. For Mandarin native person like me, it's obvious between the both - and that's why I use `（` & `）` instead of `(` & `)` in Taiwanese Mandarin translation.

> I would not fix it that way.

I have to admit it's hard to fix this bug with the current restriction. If there were no perfect solution found, I would consider the compromised ones. However, the solution provide by @softmgr works perfectly, without breaking the current contract of translation. I just don't see why we should use another solution which will make us change the translation structure.

**Comment by alankilborn** [comment]
>The symbols with the same meaning has the different representation in the different languages.

There isn't much _meaning_ to parentheses wrapping the number of hits.
It's just a convention invented for use in _Search results_; it could have just as easily been done as:
`C:\folder\file.ext - 3 hits`
or any one of many ways.
A nice convention might have been to wrap the path in double quotes, e.g. `"C:\folder\file.ext" (3 hits)` -- but I digress.

It's _interesting_, what you've done with the translation for Mandarin Chinese.
I personally don't like it (I don't have to), because it makes writing scripts to share with others for postprocessing such data _difficult_.
I'd like to be able to count on certain "markers" to be in the text data, no matter what the localization is for the data.

>the solution provide by @softmgr works perfectly

I'd delete this part: `path.find('\\') != std::wstring::npos &&`.
And... I find the comments don't add any value to the code, but that's personal preference I guess.

**Comment by softmgr** [comment]
> I'd delete this part: `path.find('\\') != std::wstring::npos &&`.
> 
> And... I find the comments don't add any value to the code, but that's personal preference I guess.
> 
> 
> 
> 

The code segment `path.find('\\') != std::wstring::npos &&` is used to determine whether the document is "new". If a new document is created but not yet saved, it will not contain the `'\\'` character.


@donho 
I don’t know how to do a PR. If you think my code is good, please just use it directly.

**Comment by alankilborn** [comment]
>I'd delete this part: path.find('\\') != std::wstring::npos &&.

> The code segment `path.find('\\') != std::wstring::npos &&` is used to determine whether the document is "new". If a new document is created but not yet saved, it will not contain the `'\\'` character.

I understand this.

However, with _Find All in All Opened Documents_ , `new X` or renamed softnamed files are possible; example:

![image](https://github.com/user-attachments/assets/d7de1670-2bd0-44c1-a4ae-0fddff1e0a6c)

User may wish to gather the names of these with _Copy Selected Pathname(s)_.
(_Open Selected Pathnames_, however, would be pointless, because all softnamed files are already open.)

**Comment by softmgr** [comment]
> User may wish to gather the names of these with _Copy Selected Pathname(s)_. (_Open Selected Pathnames_, however, would be pointless, because all softnamed files are already open.)


You’re right, I didn’t consider that thoroughly.
Additionally, I believe there’s another aspect that could be improved for usability: when the cursor is positioned on a line starting with L"Search ", it should return the list of all files from that search. This way, there’s no need to select all the files manually.
I’ve already made this adjustment, and I’m sharing it for your reference.
﻿
```

vector<wstring> Finder::getResultFilePaths(bool onlyInSelectedText) const
{
	std::vector<wstring> paths;
	size_t fromLine = 0, toLine = 0;

	if (onlyInSelectedText)
	{
		const pair<size_t, size_t> lineRange = _scintView.getSelectionLinesRange();
		fromLine = lineRange.first;
		toLine = lineRange.second;
	}
	else
	{
		toLine = _scintView.execute(SCI_GETLINECOUNT) - 1;
	}

	const bool inSearch = (toLine == 0) || // For the first line in the selection, it must start with L"Search "
		(fromLine == toLine && (_scintView.execute(SCI_GETFOLDLEVEL, toLine) & SC_FOLDLEVELHEADERFLAG)); // For other selected lines that also start with L"Search "
	if (inSearch)
		toLine = _scintView.execute(SCI_GETLINECOUNT) - 1; // Temporarily set the end line to the last line

	size_t len = _pMainFoundInfos->size();  // First, get the number of elements in the container
	for (size_t line = fromLine; line <= toLine; ++line)
	{
		bool found = false;  // Was it found?
		const int lineFoldLevel = _scintView.execute(SCI_GETFOLDLEVEL, line) & SC_FOLDLEVELNUMBERMASK;
		if (lineFoldLevel == fileHeaderLevel)
		{
			line++;  // Move to the next line
			if (line < len)
				found = true;  // Found it
		}
		else if (lineFoldLevel == resultLevel)
		{
			if (line < len)
				found = true;  // Found it
		}
		if (found)
		{
			wstring& path = (*_pMainFoundInfos)[line]._fullPath;  // Get the path from the container
			if (!path.empty() && std::find(paths.begin(), paths.end(), path) == paths.end()) // If it does not exist in the sequence container
			{
				paths.push_back(path);
			}
		}
		else
		{
			if (inSearch && (line > fromLine) && (_scintView.execute(SCI_GETFOLDLEVEL, line) & SC_FOLDLEVELHEADERFLAG)) // If the loop reaches the next line starting with L"Search ", exit the loop. This will get all file lists from the current search.
				break;
		}
	}

	return paths;
}

```

**Comment by alankilborn** [comment]
> Additionally, I believe there’s another aspect that could be improved for usability: when the cursor is positioned on a line starting with L"Search ", it should return the list of all files from that search. This way, there’s no need to select all the files manually.
> I’ve already made this adjustment, and I’m sharing it for your reference.

This was already something I was planning as a future change, but I am coordinating it with a related change.  The goal here is to not overwhelm @donho with too many changes at once -- the KISS principle.  And dropping random bits of code here and expecting others to deal with them...can be considered overwhelming -- if you want to contribute, please learn how to do PRs.

**Comment by donho** [comment]
@alankilborn 
> User may wish to gather the names of these with Copy Selected Pathname(s).

Hmm... The command name is `Copy Selected "Pathname(s)"` - the name of command is clearly indicated "Pathname(s)", so untitled name should be excluded in my opinion.

**Comment by alankilborn** [comment]
Oh, no...
So many users work only with softnamed/untitled tabs, especially those that they've renamed.
They realistically could want to get a list of those from this new feature.

There is no good substitute for the word "Pathname(s)"...; "Copy Selected Tabnames(s)" doesn't really work. 

It seems a disservice to filter out softnamed/untitled tabs.
If you note, you accepted my original PR on this issue, which purposefully did NOT filter out softnamed tabs in this way.

**Comment by alankilborn** [comment]
>Who do want to copy "foo", "bar" or "new 1" into the clipboard?

User do a lot of odd things; why prevent them from doing something that is completely logical to want/need to do, when there is zero cost for allowing it (it even makes the code shorter/simpler).

>If you've got the valid argument

Already provided.

> or any ref of discussion concerning it, I'll reconsider it.

This is rather silly, as there can't be a "ref. of discussion" on a feature that to this point hasn't existed.

>I didn't think of such case at that time. Now the point is revealed, it should be considered.

Yea... people proposing large sections of code, without even doing a PR, interfering with known contributors that provide thought-out solutions, are what got this started.  IMO the bug should have been pointed out and NO "replace everything with this and all problems are solved" should have been considered.  Leave it to the original contributor to fix the problem (perhaps after discussion about some previously unknown reasons for why certain things are...).

**Comment by pryrt** [comment]
@donho said,
> Who do want to copy "foo", "bar" or "new 1" into the clipboard?
> If you've got the valid argument,

For pasting into another document, the same as they are doing with the filenames.  If they have dozens of open tabs, some named and some not, and want to save a list of tabs an an index/table-of-contents file, they might not care that some are not saved and some are... they want to be able to exit Notepad++ and come back after the reboot, and still have that list of tabs.  (And that's just the first situation I thought of; I am sure creative users of Notepad++ could come up with dozens of unanticipated workflows where having the names of the named and unnamed tabs would come in handy to them, even though we cannot think of it.)

Further: the user selected those specific results and asked for the list of tabs that contains their matches, so they can do something with it; why should we fight the user and tell them, "no, you don't actually want _all_ the results you selected, just some of them"?  

And when it's documented in the User Manual, when I have to say "but when you copy, it will only copy the names of files that at some point were saved, not files that are new but not saved to your filesystem", that will be _virtually guaranteed_ to prompt people to come into the Forum and here and start asking for an action that includes both.  (And no, I won't just "not document that limitation to the Copy Selected Pathname(s) feature", because then when it doesn't copy the names of all the matching names, users will ask why not.)

And users who have been used to the current `Copy Pathname(s)` action copying the names of their `new N` tabs as well would be highly confused (and likely annoyed) when it stops selecting those names anymore

When the implementation as it was orignially proposed already has an ability, inherited from the previous usage which people are used to, I see no reason to put in extra work to _remove_ that feature before release, only for a user to come back and complain 6 months later, "this would have been a great feature, but since it ignores unsaved files, it's completely useless to me".  Performing more work for less functionality, and then creating more work again to add back in that intentionally-removed functionality seems like poor planning to me.

OTOH, if you really think it would be useful to _also_ have a version of the command that only grabs the names for tabs that have an entry in the filesystem, I wouldn't think there's a problem in having _both_ versions.  Actually, trying to come up with two distinct names that express the subtle differences would be nasty: maybe `Copy Selected Pathnames (exclude never-saved)` \*, or maybe adding another option-entry at the end of that right-click menu to `Exclude never-saved files from Pathname Copy`, which would then affect the action of the copy.  (*: Cannot call it "new files", because after restarting Notepad++, the user might not consider it a new file anymore, especially if they've renamed the tab without saving to their filesystem.  Cannot call it "unnamed files", because they may have renamed from `new 1` to `MyTabsName`.  Cannot call it "unsaved files", because `c:\blah.txt` after being edited but not yet saved is still an unsaved file.  The best I can come up with is "never saved", though I admit it's unwiedly.)

@alankilborn said,
> There is no good substitute for the word "Pathname(s)"...; "Copy Selected Tabnames(s)" doesn't really work.

When I first read the proposed name of "Copy Selected Pathname(s)", I wanted to actually complain "but the name as it current exists, and as proposed, doesn't fully express the feature, because it doesn't really include `new N` files", but I couldn't come up with a proposal that was _better_ than "Pathname(s)", so I hadn't chimed in yet; and before I had a chance, this new tangent of _removing_ the never-saved files from the Copy was brought up.  And I would much rather have the action name include the word "Pathname(s)" even though it includes the never-saved tabs' name as the pathname, rather than cripple the one copy of the action so that it now ignores the never-saved tabs, even though users are already used to the action including those tabs as well.

**Comment by donho** [comment]
@softmgr 
> Additionally, I believe there’s another aspect that could be improved for usability: when the cursor is positioned on a line starting with L"Search ", it should return the list of all files from that search. This way, there’s no need to select all the files manually.
I’ve already made this adjustment, and I’m sharing it for your reference.

It's confusing IMO. 

@alankilborn 
> This was already something I was planning as a future change,

Please don't.

**Comment by donho** [comment]
@pryrt 
Thank you for your very detail explanation.

Here the commit for restoring the ability of copying untitled document:
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/af2b90f0a586028afb3f26159cfaa4eaf250ed84

The behaviour of search results context menu will be freeze in this way.

**Comment by pryrt** [comment]
Well, _partial_ thumbs-up, anyway.  After reading your edit, I am not as happy with the results. :-(  

> restoring the ability of copying untitled document

I am glad you were able to restore the `new #` to the Copy command. 👍 

>  Further suggestion of changing behaviour won't be accepted in the future.

However, I was looking forward to upvoting Alan's future suggestion.  So this is a rather disappointing statement.  👎 

Unfortunately, I think that @softmgr inserting the additional request in the middle of this complicated discussion, rather than creating a separate issue, muddied the waters, and soured you on what's actually a very good idea; it shouldn't have been a part of this discussion or request, but it merits separate consideration.  🙏Would you at least allow Alan to create a new Issue, thoroughly describing what's wanted, and explaining the benefits, without the Issue being rejected immediately 🙏? If you decided to not let it be immediately implemented, that is of course your prerogative; but what Alan wanted to suggest was really the next logical step of the intuitive-usability improvements for the Search Results that Alan has been trying to incrementally work on; and I think that after the current improvements have been "live" for a little while, that the benefits of the next step that Alan wants to take will be more clearly seen, so I think at least having an open Issue on the request is important.

**Comment by vlakoff** [comment]
I was personally working the other way around:

* Cleaning up old searches, unwanted matches, etc., by placing the cursor on the relevant lines and pressing "Delete" on the keyboard
* Then using "right-click > Open Selected Pathname(s)" to open the remaining (i.e., filtered) results

But I can adapt to the new workflow. I just need to get used to doing a "Select all" beforehand, and of course, I can also take advantage of this new "partial open" feature.

One improvement, though, that would be very useful:

As it's currently implemented, please allow the use of "Open Selected Pathname(s)" on the "search header" lines—like this one:

    Search "foobar" (14 hits in 7 files of 51 searched) [Extended]

This would allow users to open the files relevant to a given search, and I think it would be incredibly useful.
