### ISSUE TITLE
Question: How can NPPN_CMDLINEPLUGINMSG be used?

### ISSUE THREAD

**Issue by Ekopalypse** [notepad-plus-plus/notepad-plus-plus#17024]
If I'm correct, NPPN_CMDLINEPLUGINMSG is only triggered [here](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/f44795a69e93010ff60593fa715f5ce3b1ba2aca/PowerEditor/src/NppBigSwitch.cpp#L833) and the only instance using WM_COPYDATA with the command line parameter seems to be called [here](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/f44795a69e93010ff60593fa715f5ce3b1ba2aca/PowerEditor/src/winmain.cpp#L773).
However, this happens in an if statement that ultimately returns from wWinMain, causing the app to terminate.
What am I missing? And does this [if](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/f44795a69e93010ff60593fa715f5ce3b1ba2aca/PowerEditor/src/winmain.cpp#L773) make any sense at all?

**Comment by Ekopalypse** [comment]
The only way I have found so far to receive the notification is in the following scenario:
Running in mono-instance mode.
```
C:\PortableApps\npp\notepad++.exe  -pluginMessage="NppLspClient=."
-> NO notification sent
run a 2nd C:\PortableApps\npp\notepad++.exe  -pluginMessage="NppLspClient=."
-> notification sent to first instance
-> 2nd instance terminates
```
But this scenario seems pointless, doesn't it?

**Comment by donho** [comment]
> However, this happens in an if statement that ultimately returns from wWinMain, causing the app to terminate.
What am I missing? And does this [if](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/f44795a69e93010ff60593fa715f5ce3b1ba2aca/PowerEditor/src/winmain.cpp#L773) make any sense at all?

In mono-instance mode, when the 1st Notepad++ instance is detected in winmain of the 2nd instance on its startup, the 2nd passes the argument to the 1st one and quit. That explains what you observed:

```
run a 2nd C:\PortableApps\npp\notepad++.exe  -pluginMessage="NppLspClient=."
-> notification sent to first instance
-> 2nd instance terminates
```
And it makes sense.


However the arguments of the 1st launch should always reach to the 1st instance, so the following:
```
C:\PortableApps\npp\notepad++.exe  -pluginMessage="NppLspClient=."
-> NO notification sent
```
is a bug.

I'll keep you posted when I find somethings.

**Comment by Ekopalypse** [comment]
Thank you for working on this, and just to clarify: I am referring to the `if` in connection with sending the command line argument. I would even go so far as to say that the if check, not multiInst mode and not first instance, is exactly the case where the notification does not need to be sent.

**Comment by donho** [comment]
Please check PR #17027 which should fix the issue.

**Comment by Ekopalypse** [comment]
Thx, yes, I see the message; tested with the release artifact for x64.
BUT the problem that when a mono instance is running and a second instance is started, the first instance sends the notification initiated by the second instance still persists.

**Comment by donho** [comment]
> BUT the problem that when a mono instance is running and a second instance is started, the first instance sends the notification initiated by the second instance still persists.

It's not a bug but a feature. 
All the Notepad++ CLI arguments have the same behaviour - so users can use Notepad++ command to change or add what they want in the only Notepad++ instance. For example:
`notepad++.exe a.txt` will open a.txt in Notepad++ 
`notepad++.exe b.txt -n8964` will open b.txt in Notepad++ and scroll to line 8964
`notepad++.exe a.txt -n2758` will switch to a.txt and scroll to line 2758 

For plugin, I can imagine `notepad++.exe -pluginMessage="NppLspClientChangeLang=cpp"` for changing the language to C++, or `-pluginMessage="NppLspClientLagSvrAddr=js-192.168.86.96:69"` to add/change server address, via command line, without restarting. It could be a way for plugin to allow users to configure it without implementing the GUI.

**Comment by Ekopalypse** [comment]
Fair enough, thx for the fix and your ongoing work to improve Npp.
