### ISSUE TITLE
Notepad++ does not recognice PHP functions in Function List

### ISSUE THREAD

**Issue by AleWin32** [notepad-plus-plus/notepad-plus-plus#1919]
Having a PHP file opened and selecting PHP language (Language menu, P, PHP), Notepad++ does not recognise the functions in Function List if they are like:

function getInfoTravel ($param1, &param2)
{
...
}

If we remove the space OR SPACES after the function name (getInfoTravel) it is recognised:

function getInfoTravel($param1, &param2)
{
...
}

Please, add to the regular expression that parse the PHP files the possibility to have one or more spaces after the function name.

**Comment by xamount** [comment]
A similar problem happens with PHP function marked as static. e.g

```
<?

static function alpha($arg)
{
        return true;
    
} 

?>
```
Nothing shows in the function list

**Comment by MAPJe71** [comment]
Try this parser:

    <parser
        id         ="php_syntax" 
        displayName="PHP" 
        commentExpr="(?'MLC'(?s-m)/\*.*?\*/)|(?'SLC'(?m-s)(?:#|/{2}).*$)|(?'STRLIT'(?s-m)&quot;[^&quot;\\]*(?:\\.[^&quot;\\]*)*&quot;|&apos;[^&apos;\\]*(?:\\.[^&apos;\\]*)*&apos;)"
      >
      <function
          mainExpr="\s*(?-i:function)(?:\s+|[*&amp;]\s*|\s*[*&amp;]|\s*[*&amp;]\s*)(?:\b(?!(?-i:if|while|for|switch)\b))[A-Za-z_\x7f-\xff][\w\x7f-\xff]*\s*\([^{]*\{"
        >
        <functionName>
          <nameExpr expr="(?:\b(?!(?-i:if|while|for|switch)\b))[A-Za-z_\x7f-\xff][\w\x7f-\xff]*\s*\(" />
          
          <nameExpr expr="[A-Za-z_\x7f-\xff][\w\x7f-\xff]*" />
        </functionName>
      </function>
    </parser>

**Comment by MAPJe71** [comment]
@AleWin32 & @xamount 
Did my changes to the PHP function parser give you the expected result?

**Comment by MAPJe71** [comment]
@AleWin32 & @xamount 

Any kind of feedback would be appreciated.

**Comment by xamount** [comment]
I pasted your parser in functionList.xml and reloaded Notepad++ version 7.1. It did not help unfortunately.

**Comment by MAPJe71** [comment]
@xamount 
Nothing is shown in the FunctionList tree?
Maybe you edited the wrong functionList.xml file as there might be more than one on your system.
Check for ...
1. `%ProgramFiles%\Notepad++\functionList.xml`;
2. `%ProgramFiles(x86)%\Notepad++\functionList.xml`;
3. `%AppData%\Notepad++\functionList.xml`

**Comment by xamount** [comment]
I edited #2. Then I found another functionList.xml in %AppData%\Roaming\Notepad++\ and edited that as well. Still no luck.

**Comment by MAPJe71** [comment]
@xamount Could you provide an example file?

**Comment by xamount** [comment]
It doesn't look like I can attach a .php file. But try one with the following content:

<?

static function alpha($arg)
{
        return true;

} 

?>

**Comment by MAPJe71** [comment]
![capture-2016-10-20-01 00 09](https://cloud.githubusercontent.com/assets/6494038/19540557/ae0aa446-9660-11e6-89e8-336e1a020190.png)

**Comment by xamount** [comment]
<?xml version="1.0" encoding="UTF-8" ?>

<NotepadPlus>
	<functionList>
		<associationMap>
		
			<association langID= "1" id="php_function" />
			<association langID= "2" id="c_function" />
			<association langID= "3" id="cpp_function" />
			<association langID= "4" id="cs_function" />
			<association langID= "6" id="java" />
			<association langID= "9" id="xml_node" />
			<association langID="12" id="batch_label" />
			<association langID="13" id="ini_section" />
			<association langID="21" id="perl_function" />
			<association langID="22" id="python_function" />
			<association langID="26" id="bash_function" />
			<association langID="28" id="nsis_syntax" />
			<association langID="36" id="ruby_function" />
			<association langID="58" id="javascript_function" />

		</associationMap>
		<parsers>

			<parser
				id         ="php_function"
				displayName="PHP"
				commentExpr="(?s:/\*.*?\*/)|(?m-s://.*?$)"
			>
				<classRange
					mainExpr    ="^\s*(class|abstract\s+class|final\s+class)[\t\x20]+[A-Za-z_\x7f-\xff][\w\x7f-\xff]*(\s*|\s*(extends|implements|(extends\s+(\\|[A-Za-z_\x7f-\xff][\w\x7f-\xff]*)+\s+implements))\s+(\,\s*|(\\|[A-Za-z_\x7f-\xff][\w\x7f-\xff]*))+\s*)?\{"
					openSymbole ="\{"
					closeSymbole="\}"
				>
					<className>
						<nameExpr expr="(class|abstract\s+class|final\s+class)\s+\w+" />
						<nameExpr expr="\s+\w+\Z" />
						<nameExpr expr="\w+\Z" />
					</className>
					<function
						mainExpr="^\s*((static|public|protected|private|final)*(\s+(static|public|protected|private|final))+\s+)?(function\s+)+(\w+(\s+\w+)?(\s+|\*\s+|\s+\*|\s+\*\s+))?(\w+\s*::)?(?!(if|while|for|switch))[\w~]+\s*\([^\{]*\{"
					>
						<functionName>
							<funcNameExpr expr="(?!(if|while|for|switch))\w+\s*\([^\{]*" />
							
							<funcNameExpr expr="(?!(if|while|for|switch))\w+" />
						</functionName>
					</function>
				</classRange>
				<function
					mainExpr="^\s*function\s+\w+\("
				>
					<functionName>
						<nameExpr expr="(?!(if|while|for))\w+\s*\(" />
						<nameExpr expr="(?!(if|while|for))\w+" />
					</functionName>
					<className>
						<nameExpr expr="\w+(?=\s*::)" />
					</className>
				</function>
			</parser>
			
<parser
    id         ="php_syntax" 
    displayName="PHP"
    commentExpr="(?'MLC'(?s-m)/\*.*?\*/)|(?'SLC'(?m-s)(?:#|/{2}).*$)|(?'STRLIT'(?s-m)&quot;[^&quot;\\]*(?:\\.[^&quot;\\]*)*&quot;|&apos;[^&apos;\\]*(?:\\.[^&apos;\\]*)*&apos;)"
  >
  <function
      mainExpr="\s*(?-i:function)(?:\s+|[*&amp;]\s*|\s*[*&amp;]|\s*[*&amp;]\s*)(?:\b(?!(?-i:if|while|for|switch)\b))[A-Za-z_\x7f-\xff][\w\x7f-\xff]*\s*\([^{]*\{"
    >
    <functionName>
      <nameExpr expr="(?:\b(?!(?-i:if|while|for|switch)\b))[A-Za-z_\x7f-\xff][\w\x7f-\xff]*\s*\(" />
      
      <nameExpr expr="[A-Za-z_\x7f-\xff][\w\x7f-\xff]*" />
    </functionName>
  </function>
</parser>

			<parser
				id         ="c_function"
				displayName="C source"
				commentExpr="(?s:/\*.*?\*/)|(?m-s://.*?$)"
			>
				<function
					mainExpr="^[\t\x20]*((static|const|virtual)\s+)?[\w:]+(\s+\w+)?(\s+|(\*|\*\*)\s+|\s+(\*|\*\*)|\s+(\*|\*\*)\s+)(\w+\s*::)?(?!(if|while|for))\w+\s*\([^\)\(]*\)(\s*const\s*)?[\n\s]*\{"
				>
					<functionName>
						<nameExpr expr="(?!(if|while|for))[\w~]+\s*\(" />
						<nameExpr expr="(?!(if|while|for))[\w~]+" />
					</functionName>
				</function>
			</parser>

			<parser
				id         ="cpp_function"
				displayName="C++ Class"
				commentExpr="(?s:/\*.*?\*/)|(?m-s://.*?$)"
			>
				<classRange
					mainExpr    ="^[\t\x20]*(class|struct)[\t\x20]+\w+\s*(final)?\s*(:\s*(public|protected|private)\s+\w+\s*)?\{"
					openSymbole ="\{"
					closeSymbole="\}"
				>
					<className>
						<nameExpr expr="(class|struct)[\t\x20]+\w+" />
						<nameExpr expr="[\t\x20]+\w+" />
						<nameExpr expr="\w+" />
					</className>
					<function
						mainExpr="^[\t\x20]*((static|const|virtual)\s+)?(\w+(\s+\w+)?(\s+|(\*|\*\*|&amp;)\s+|\s+(\*|\*\*|&amp;)|\s+(\*|\*\*|&amp;)\s+))?(\w+\s*::)?(?!(if|while|for|switch))[\w~]+\s*\([^\)\(]*\)(\s*const\s*)?(\s*(final|override|final\s*override|override\s*final)\s*)?[\n\s]*\{"
					>
						<functionName>
							<funcNameExpr expr="(?!(if|while|for|switch))[\w~]+\s*\(" />
							<funcNameExpr expr="(?!(if|while|for|switch))[\w~]+" />
						</functionName>
					</function>
				</classRange>
				<function
					mainExpr="^[\t\x20]*((static|const|virtual)\s+)?\w+(\s+\w+)?(\s+|(\*|\*\*|&amp;)\s+|\s+(\*|\*\*|&amp;)|\s+(\*|\*\*|&amp;)\s+)(\w+\s*::)?(?!(if|while|for))\w+\s*\([^\)\(]*\)(\s*const\s*)?[\n\s]*\{"
				>
					<functionName>
						<nameExpr expr="(?!(if|while|for))\w+\s*\(" />
						<nameExpr expr="(?!(if|while|for))\w+" />
					</functionName>
					<className>
						<nameExpr expr="\w+(?=\s*::)" />
					</className>
				</function>
			</parser>

			<parser
				id         ="cs_function"
				displayName="C# Class"
				commentExpr="(?s:/\*.*?\*/)|(?m-s://.*?$)"
			>
				<classRange
					mainExpr    ="^[\t\x20]*((public|protected|private|internal)\s+)?(\w+\s*)?(class|struct|interface)[\t\x20]+[^\{]+\{"
					openSymbole ="\{"
					closeSymbole="\}"
				>
					<className>
						<nameExpr expr="(class|struct|interface)[\t\x20]+\w+" />
						<nameExpr expr="[\t\x20]+\w+" />
						<nameExpr expr="\w+" />
					</className>
					<function
						mainExpr="^[^\S\r\n]*(?&lt;modifier1&gt;(?:public|protected|internal|private)\s*)?(?&lt;modifier2&gt;(?:new|static|virtual|sealed|override|abstract|extern)\s*)?(partial\s*)?(?&lt;type&gt;(?!(return|if|else))\w+(?&lt;genericType&gt;&lt;[\w,\s&lt;&gt;]+&gt;)?\s+)(?&lt;name&gt;\w+(?&lt;genericNameType&gt;&lt;[\w,\s&lt;&gt;]+&gt;)?\s?)\((?&lt;params&gt;[\w\s,&lt;&gt;\[\]\:=\.]*)\)(?&lt;ctorChain&gt;\s*\:\s*(?:base|this)\s*\((?&lt;ctorParams&gt;[\w\s,&lt;&gt;\[\]\:=\.]*)\))?[\w\s&lt;&gt;\:,\(\)\[\]]*(?:\{|;)"
					>
						<functionName>
							<funcNameExpr expr="(\w+(&lt;[\w,\s&lt;&gt;]+&gt;)?\s?)\(" />
							<funcNameExpr expr="(\w+(&lt;[\w,\s&lt;&gt;]+&gt;)?\s?)" />
						</functionName>
					</function>
				</classRange>
			</parser>

			<parser
				id         ="java"
				displayName="Java"
				commentExpr="(?s:/\*.*?\*/)|(?m-s://.*$)"
			>
				<classRange
					mainExpr    ="^[\t\x20]*((public|protected|private|static|final|abstract|synchronized|@(\w)+)\s+)*(class|enum|interface|@interface)\s+\w+(&lt;\s*\w+(,\s*\w+)*\s*&gt;)?(\s+extends\s+\w+)?(\s+implements\s+\w+(,\s*\w+)*)?\s*\{"
					openSymbole ="\{"
					closeSymbole="\}"
				>
					<className>
						<nameExpr expr="(class|enum|interface|@interface)\s+\w+(&lt;\s*\w+(,\s*\w+)*\s*&gt;)?" />
						<nameExpr expr="\s+\w+(&lt;\s*\w+(,\s*\w+)*\s*&gt;)?" />
						<nameExpr expr="\w+(&lt;\s*\w+(,\s*\w+)*\s*&gt;)?" />
					</className>
					<function
						mainExpr="^[\t\x20]*((public|protected|private|static|final|abstract|synchronized|@(\w)+)\s+)*(\w*(\[\s*])*\s+)?(?!(if|while|for|switch|catch|synchronized)\b)\w+(\[\s*])*(&lt;\s*\w+(,\s*\w+)*\s*&gt;)?\s*\([^\)\(]*\)(\s+throws\s+\w+)?\s*\{"
					>
						<functionName>
							<funcNameExpr expr="(?!(if|while|for|switch|catch|synchronized)\b)\w+(\[\s*])*(&lt;\s*\w+(,\s*\w+)*\s*&gt;)?\s*\(" />
							<funcNameExpr expr="(?!(if|while|for|switch|catch|synchronized)\b)\w+(\[\s*])*(&lt;\s*\w+(,\s*\w+)*\s*&gt;)?" />
						</functionName>
					</function>
				</classRange>
			</parser>

			<parser
				id         ="xml_node"
				displayName="XML Node"
				commentExpr="&lt;!--([^-]|-(?!-&gt;))*--&gt;"
			>
				
				<function
					mainExpr="&lt;[\w\?]+[\t\x20]+\w+[\t\x20]*=[\t\x20]*&quot;[^&quot;]+&quot;"
				>
					<functionName>
						<nameExpr expr="[^&lt;]*" />
					</functionName>
				</function>
			</parser>

			<parser
				id         ="batch_label"
				displayName="BAT Label"
				commentExpr="(?m-s)(::.*?$)|(REM.*?$)"
			>
				<function
					mainExpr="^[\t\x20]*:\w+"
				>
					<functionName>
						<nameExpr expr="[^\t\x20:]*" />
					</functionName>
				</function>
			</parser>

			<parser
				id         ="ini_section"
				displayName="INI Section"
				commentExpr="(?m-s:[#;].*?$)"
			>
				<function
					mainExpr="^[\t\x20]*[\[&quot;][\w.;\x20\(\)-]+[\]&quot;]"
				>
					<functionName>
						<nameExpr expr="[^\[\]&quot;]*" />
					</functionName>
				</function>
			</parser>

			<parser
				id         ="perl_function"
				displayName="Perl"
			>
				<function
					mainExpr="^\s*(?&lt;!#)\s*sub\s+\w+\s*\(?[^\)\(]*?\)?[\n\s]*\{"
				>
					<functionName>
						<nameExpr expr="(sub\s+)?\K\w+" />
					</functionName>
					<className>
						<nameExpr expr="\w+(?=\s*::)" />
					</className>
				</function>
			</parser>

			<parser
				id         ="python_function"
				displayName="Python class"
				commentExpr="(?s:'''.*?''')|(?m-s:#.*?$)"
			>
				<classRange
					mainExpr    ="(?&lt;=^class\x20).*?(?=\n\S|\Z)"
				>
					<className>
						<nameExpr expr="\w+(?=[\(|:])" />
					</className>
					<function
						mainExpr="(?&lt;=def\x20).+?(?=:)"
					>
						<functionName>
							<funcNameExpr expr=".*" />
						</functionName>
					</function>
				</classRange>
				<function
					mainExpr="(?&lt;=def\x20).+?(?=:)"
				>
					<functionName>
						<nameExpr expr=".*" />
					</functionName>
				</function>
			</parser>

			<parser
				id         ="bash_function"
				displayName="Shell"
				commentExpr="(?m-s:#.*?$)"
			>
				<function
					mainExpr="^[\t\x20]*(function[\t\r\n\x20]*)?(\w)+[\t\r\n\x20]*(\([^\)]*\))?[\t\r\n\x20]*(\{)[^(\})\r\n\t\x20]*"
				>
					<functionName>
						<nameExpr expr="[^{]*" />
					</functionName>
				</function>
			</parser>

			<parser
				id         ="nsis_syntax"
				displayName="NSIS Syntax"
				commentExpr="(?s:/\*.*?\*/)|(?m-s:[#;].*?$)"
			>
				<function
					mainExpr="^[\t\x20]*(!macro|Function|Section|SectionGroup)[\t\x20]+[^\r\n]*$"
				>
					<functionName>
						<nameExpr expr="(?(?=[\t\x20]*!macro)[\t\x20]*!macro[\t\x20]+[^\s]+|[^\r\n]*)" />
					</functionName>
				</function>
			</parser>

			<parser
				id         ="ruby_function"
				displayName="Ruby"
			>
				
				<classRange
					mainExpr    ="(?&lt;=^class\x20).*?(?=\n\S|\Z)"
				>
					<className>
						<nameExpr expr="\w+" />
					</className>
					<function
						mainExpr="^\s*def\s+\w+"
					>
						<functionName>
							<funcNameExpr expr="(?&lt;=def\s)\w+" />
						</functionName>
					</function>
				</classRange>
				
				<function
					mainExpr="^\s*def\s+\w+"
				>
					<functionName>
						<nameExpr expr="(?&lt;=def\s)\w+" />
					</functionName>
				</function>
			</parser>

			<parser
				id         ="javascript_function"
				displayName="Javascript"
				commentExpr="(?s:/\*.*?\*/)|(?m-s://.*?$)"
			>
				<function
					mainExpr="((^|\s+|[;\}\.])([A-Za-z_]\w*\.)*[A-Za-z_]\w*\s*[=:]|^|[\s;\}]+)\s*function(\s+[A-Za-z_]?\w*\([^\)\(]*\)|\([^\)\(]*\))[\n\s]*\{"
				>
					<functionName>
						<nameExpr expr="[A-Za-z_]\w*\s*[=:]|[A-Za-z_]?\w*\s*\(" />
						<nameExpr expr="[A-Za-z_]?\w*" />
					</functionName>
					<className>
						<nameExpr expr="([A-Za-z_]\w*\.)*[A-Za-z_]\w*\." />
						<nameExpr expr="([A-Za-z_]\w*\.)*[A-Za-z_]\w*" />
					</className>
				</function>
			</parser>
            
		</parsers>
	</functionList>
</NotepadPlus>

**Comment by xamount** [comment]
There must be something going on with my functionList.xml or my environment then.

**Comment by MAPJe71** [comment]
LOL you didn't have to post you're complete functionList.xml. Just saying from which release it is would have been enough.

I have to admit I didn't generate the screen dump with an afficial released functionList.xml.
This is the (incomplete as class range not functional) one I used:
``` XML
			<parser
				displayName="PHP"
				id         ="php_syntax"
				commentExpr="(?x)                                               # Utilize inline comments (see `RegEx - Pattern Modifiers`)
								(?s:/\*.*?\*/)                                  # Multi Line Comment
							|	(?m-s:(?:\#|/{2}).*$)                           # Single Line Comment 1 and 2
							|	(?s:&quot;(?:[^&quot;\\]|\\.)*&quot;)           # String Literal - Double Quoted
							|	(?s:&apos;(?:[^&apos;\\]|\\.)*&apos;)           # String Literal - Single Quoted
							|	(?:                                             # Here Document
									&lt;{3}(?'HDID'[A-Za-z_\x7f-\xff][\w\x7f-\xff]*)[^\r\n]*\R
									(?s:.*?)
									\R\k'HDID'                                  # close with exactly the same identifier, in the first column
								)
							|	(?:                                             # Now Document
									&lt;{3}&apos;(?'NDID'[A-Za-z_\x7f-\xff][\w\x7f-\xff]*)&apos;[^\r\n]*\R
									(?s:.*?)
									\R\k'NDID'                                  # close with exactly the same identifier, in the first column
								)
							"
			>
				<classRange
					mainExpr    ="(?x)                                          # Utilize inline comments (see `RegEx - Pattern Modifiers`)
							^
							\s*
							(?:(?-i:abstract|final)\s+)?
							(?-i:class)
							\h+
							(?'VALID_ID'                                        # valid identifier, use as subroutine
								\b(?!(?-i:
									a(?:bstract|nd|rray|s)|
									b(?:ool|reak)|
									c(?:a(?:llable|se|tch)|l(?:ass|one)|on(?:st|tinue))|
									d(?:e(?:clare|fault)|ie|o)|
									e(?:cho|lse(?:if)?|mpty|nd(?:declare|for(?:each)?|if|switch|while)|val|x(?:it|tends))|
									f(?:alse|loat|inal|or(?:each)?|unction)|
									g(?:lobal|oto)|
									i(?:f|mplements|n(?:clude(?:_once)?|st(?:anceof|eadof)|t(?:erface)?)|sset)|
									n(?:amespace|ew|u(?:ll|meric))|
									o(?:r|bject)|
									p(?:r(?:i?:(nt|vate)|otected)|ublic)|
									re(?:quire(?:_once)?|turn)|
									s(?:t(?:atic|ring)|witch)|
									t(?:hrow|r(?:ait|ue|y))|
									u(?:nset|se)|
									mixed|list|var|while|xor|
									__(?:halt_compiler|(?:CLASS|DIR|F(?:ILE|UNCTION)|LINE|METHOD|NAMESPACE|TRAIT)__)
								)\b)                                            # keywords, not to be used as identifier
								[A-Za-z_\x7f-\xff][\w\x7f-\xff]*                # valid character combination for identifiers
							)
							(
								\s+
								(?:
									extends
								|
									implements
								|
									extends
									\s+
									(?:
										\\                                      # continue-on-next-line indicator
									|
										(?&amp;VALID_ID)                        # call subroutine
									)+
									\s+
									implements
								)
								\s+
								(?:
									,
									\s*
								|
									(?:
										\\                                      # continue-on-next-line indicator
									|
										(?&amp;VALID_ID)                        # call subroutine
									)
								)+
							)?
							\s*\{                                               # start of class body
						"
					openSymbole ="\{"
					closeSymbole="}"
				>
					<className>
						<nameExpr expr="(?:(?-i:abstract|final)\s+)?(?-i:class)\h+[A-Za-z_\x7f-\xff][\w\x7f-\xff]*" />
						<nameExpr expr="\s+[A-Za-z_\x7f-\xff][\w\x7f-\xff]*\Z" />
						<nameExpr expr="[A-Za-z_\x7f-\xff][\w\x7f-\xff]*\Z" />
					</className>
					<function
						mainExpr="(?x)                                          # Utilize inline comments (see `RegEx - Pattern Modifiers`)
								\s*
								(?:
									(?-i:static|public|protected|private|final)*
									(
										\s+
										(?-i:static|public|protected|private|final)
									)+
									\s+
								)?
								(?-i:function\s+)
								(?:
									(?'VALID_ID'                                # valid identifier, use as subroutine
										\b(?!(?-i:
											a(?:bstract|nd|rray|s)|
											b(?:ool|reak)|
											c(?:a(?:llable|se|tch)|l(?:ass|one)|on(?:st|tinue))|
											d(?:e(?:clare|fault)|ie|o)|
											e(?:cho|lse(?:if)?|mpty|nd(?:declare|for(?:each)?|if|switch|while)|val|x(?:it|tends))|
											f(?:alse|loat|inal|or(?:each)?|unction)|
											g(?:lobal|oto)|
											i(?:f|mplements|n(?:clude(?:_once)?|st(?:anceof|eadof)|t(?:erface)?)|sset)|
											n(?:amespace|ew|u(?:ll|meric))|
											o(?:r|bject)|
											p(?:r(?:i?:(nt|vate)|otected)|ublic)|
											re(?:quire(?:_once)?|turn)|
											s(?:t(?:atic|ring)|witch)|
											t(?:hrow|r(?:ait|ue|y))|
											u(?:nset|se)|
											mixed|list|var|while|xor|
											__(?:halt_compiler|(?:CLASS|DIR|F(?:ILE|UNCTION)|LINE|METHOD|NAMESPACE|TRAIT)__)
										)\b)                                    # keywords, not to be used as identifier
										[A-Za-z_\x7f-\xff][\w\x7f-\xff]*        # valid character combination for identifiers
									)
									(?:
										\s+
										(?&amp;VALID_ID)                        # call subroutine
									)?
									(?:\s+|\*\s+|\s+\*|\s+\*\s+)
								)?
								(?:
									(?&amp;VALID_ID)                            # call subroutine
									\s*
									:{2}
								)?
								(?&amp;VALID_ID)                                # call subroutine
								\s*\(                                           # start of function arguments
								[^{]*\{                                         # start of function body
							"
					>
						<functionName>
							<funcNameExpr expr="[A-Za-z_\x7f-\xff][\w\x7f-\xff]*\s*\([^{]*" />
							<!-- comment out the following node to display the method with its parameters -->
							<funcNameExpr expr="[A-Za-z_\x7f-\xff][\w\x7f-\xff]*" />
						</functionName>
					</function>
				</classRange>
				<function
					mainExpr="(?x)                                              # Utilize inline comments (see `RegEx - Pattern Modifiers`)
							\s*
							(?-i:function)
							(?:\s+|[*&amp;]\s*|\s*[*&amp;]|\s*[*&amp;]\s*)
							(?'VALID_ID'                                        # valid identifier, use as subroutine
								\b(?!(?-i:
									a(?:bstract|nd|rray|s)|
									b(?:ool|reak)|
									c(?:a(?:llable|se|tch)|l(?:ass|one)|on(?:st|tinue))|
									d(?:e(?:clare|fault)|ie|o)|
									e(?:cho|lse(?:if)?|mpty|nd(?:declare|for(?:each)?|if|switch|while)|val|x(?:it|tends))|
									f(?:alse|loat|inal|or(?:each)?|unction)|
									g(?:lobal|oto)|
									i(?:f|mplements|n(?:clude(?:_once)?|st(?:anceof|eadof)|t(?:erface)?)|sset)|
									n(?:amespace|ew|u(?:ll|meric))|
									o(?:r|bject)|
									p(?:r(?:i?:(nt|vate)|otected)|ublic)|
									re(?:quire(?:_once)?|turn)|
									s(?:t(?:atic|ring)|witch)|
									t(?:hrow|r(?:ait|ue|y))|
									u(?:nset|se)|
									mixed|list|var|while|xor|
									__(?:halt_compiler|(?:CLASS|DIR|F(?:ILE|UNCTION)|LINE|METHOD|NAMESPACE|TRAIT)__)
								)\b)                                            # keywords, not to be used as identifier
								[A-Za-z_\x7f-\xff][\w\x7f-\xff]*                # valid character combination for identifiers
							)
							\s*\(                                               # start of function arguments
							[^{]*\{                                             # start of function body
						"
				>
					<functionName>
						<nameExpr expr="[A-Za-z_\x7f-\xff][\w\x7f-\xff]*\s*\([^{]*" />
						<!-- comment out the following node to display the function with its parameters -->
						<nameExpr expr="[A-Za-z_\x7f-\xff][\w\x7f-\xff]*" />
					</functionName>
				</function>
			</parser>
```

**Comment by vlakoff** [comment]
The [screenshot above](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/1919#issuecomment-254965613) is incorrect, as the issue happens when there is a space between function name and opening parenthesis.

So, I could reproduce the issue. I tried before and after #2335, fails in both.

The issue happens only if the function is global, it doesn't happen if it is defined inside a class.

**Comment by MAPJe71** [comment]
My screenshot was about the _second_ issue
> A similar problem happens with PHP function marked as static.

#2335 didn't (or at least should not have) any impact on the functionality for the majority of the parsers.
An obvious mistake with the Python parser was fixed. So testing with before and after #2335 will have the same effect for the PHP parser, as you discovered.

**Comment by vlakoff** [comment]
Didn't notice there was a second issue.

Though current code is correct. "static function" is valid only for class methods, not global functions.

**Comment by bauinformatiker** [comment]
Exchanging the code section <parse ... /parse> for PHP from @MAPJe71 into the file
 functionList.xml
from the folder
C:\Users\<user>\AppData\Roaming\notepad++\
worked for me perfectly!

**Comment by AleWin32** [comment]
I don't know why @donho closes this, the bug still happens in last Notepad++ (7.5.8).

So, if you have this PHP code:

```PHP
<?php

function func1 ($param)
{
	return 1;
}

function func2 ($param)
{
	return 2;
}
?>
```

Function list is empty! You must delete the space char between the function name and the parentheses to be able to list it.

Please, reopen this issue.

**Comment by vlakoff** [comment]
This case is supposedly fixed, you are probably using an older `functionList.xml` file (location: C:\Users\\[username]\AppData\Roaming\Notepad++\functionList.xml). If I recall correctly, Notepad++ doesn't replace it when updating the program. So, try manually replacing this file with the latest one.

**Comment by AleWin32** [comment]
Thanks @vlakoff I replaced that file with the new one and is solved
