### ISSUE TITLE
Spaces get converted to tabs

### ISSUE THREAD

**Issue by aaronmcdavid** [notepad-plus-plus/notepad-plus-plus#2215]
### Description of the Issue

Spaces get converted to tabs and there is no option to turn this off
### Steps to Reproduce the Issue

1. Type the following:
   `\tThis line has one tab\tAnd then another«Enter»`
2. Type the following:
   `«21 spaces»\tThis line has an auto-indent tab, some spaces, and a manual tab«Enter»`
### Expected Behavior

I expected NotePad++ to leave my spaces and tabs alone.  I know what's best for my file.  Also, when I hit Enter, the next line should be indented with the same combination of whitespace the previous line was, not Notepad++'s choice.
### Actual Behavior

NotePad++ converted my spaces to tabs.  There's a feature to turn on converting tabs to spaces, but there seems to be no way to turn off converting spaces to tabs.  Leave my whitespace alone!
### Motivation

By mixing tabs and spaces, I guarantee that users of any tab width setting get the indentation they expect.

**Comment by aaaxx** [comment]
I think this is by design. You will notice that it only happens at the beginning of the line; that is, only when there is nothing except some combination of spaces and tabs between the beginning of the line and the caret. It seems to be a safeguard against mixing tabs and spaces, while still allowing you to use tabs for indentation correctly (i.e. tabs for current indent level and spaces for further alignment).

**Comment by aaronmcdavid** [comment]
By design or no, it's a "feature" that I wish I could turn off.  Until it's fixed, I've switched to Atom; NotePad++ has nice features, but screwing with my whitespace is enough to push me to use something that doesn't.

Judging by the success I have in my source code files of mixing tabs and spaces both at the beginning of the line and in the middle to generate nicely spaced code, I conclude your second paragraph is mistaken.

**Comment by sm4rk0** [comment]
Is this one related to or maybe even duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/821 ?

**Comment by aaronmcdavid** [comment]
I think it's a related issue, but not the same.  I think if #821 were solved, this issue could be included as part of the solution.  For example, there could be a radio selection or K&R auto-indent or Whitesmiths auto-indent, and others.  Similarly, there could be a radio selection for "auto-indent with same whitespace as previous line", "auto-indent with spaces", and "auto-indent with tabs".  Last, (this issue), you could have a radio button for "convert initial whitespace to spaces", "convert initial whitespace to tabs", and "leave initial whitespace unchanged".

**Comment by baarney** [comment]
Just a +1 for this request, and an agreement that #821is not quite the same. There appear to be a number of ways of getting the indentation to the same level as the previous line (NppAutoIndent -> Previous Line etc.), but everything I have seen still makes up its own mind on what combination of tabs and spaces to use to achieve that indentation.

It seems so simple in principle:

- If I press -tab- I want a tab.
- If I press -space- I want a space.
- If I press -enter- at the end of a line, I want the next line indented with exactly the same leading whitespace chars as the previous line.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Comment by sm4rk0** [comment]
Why closing valid unresolved issues?

**Comment by baarney** [comment]
I have updated to 7.6.6 and as far as I can see this issue persists.
Please re-open this bug, or at least add some comment as to why it will not be fixed.
