### ISSUE TITLE
Pressing "Save all" by mistake on many unsaved documents causes multiple Save As dialogs

### ISSUE THREAD

**Issue by klanderfri** [notepad-plus-plus/notepad-plus-plus#2929]
### Description of the Issue
My workflow causes me to have 20+ unsaved documents open in Notepad++ that are never to be saved.
Sometimes I press "Save All" by mistake which causes multiple "Save As" dialogs. This forces me to select 
"Cancel" on a lot of dialogs.

### Steps to Reproduce the Issue
1. Create several documents and make sure they are changed and unsaved (Ctrl+N, then add some text into the document).
2. Ctrl+Shift+S
3. Press Cancel.
4. Press Cancel again.
5. And again...

### Expected Behavior
If the user presses Cancel then this choice should be applied to all subsequent dialogs.

### Actual Behavior
Every Save As are treated like an independent operation with no regard to previous user choices.

### Important
This issue is about unsaved documents that never been saved, ie only exists within the Notepad++ context.
Having several existing documents open, but unsaved, will NOT trigger the problem described in this issue.

### Debug Information
Notepad++ v7.3.2   (32-bit)
Build time : Feb 12 2017 - 23:15:39
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : HTMLTag_unicode.dll mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll PluginManager.dll

**Comment by Carbone13** [comment]
same problem here

**Comment by redmanmale** [comment]
See also #2724.
That dialog - Yes/No for all - seems like a more convenient solution for this, because your option - 'Cancel then this choice should be applied to all subsequent dialogs' is counter-intuitive imo.

**Comment by salvarani** [comment]
"Cancel" button + "[X] Apply to all subsequent documents" checkbox
looks like the best solution to me.

**Comment by donho** [comment]
This issue has been fixed by new added buttons "Yes to All" and "No to All".

**Comment by klanderfri** [comment]
> This issue has been fixed by new added buttons "Yes to All" and "No to All".

In which version is this issue fixed? :-)

**Comment by sasumner** [comment]
>In which version is this issue fixed?

the "...to all" additional buttons first appeared in v. 7.8[.0]

**Comment by klanderfri** [comment]
I have version 7.8.2 (32-bit Windows, built 2019-12-04 01:36:59) and when I go through the original steps to reproduce I get several "Save As..." dialogs, one for each unsaved file. I have to press Cancel in each.

In my opinion, this issue is NOT fixed and needs to be reopened.

**Comment by klanderfri** [comment]
I have version 7.8.2 (32-bit Windows, built 2019-12-04 01:36:59) and when I go through the original steps to reproduce I get several "Save As..." dialogs, one for each unsaved file. I have to press Cancel in each.

In my opinion, this issue is NOT fixed and needs to be reopened.

**Comment by klanderfri** [comment]
Reviewing this issue and other linked issue makes me draw the conclusion that there has been a misunderstanding. The documents I refer to in the issue is not saved, and has never been. Step 1 in the "steps to reproduce" is based on Ctrl+N, not on Ctrl+O.

I have edited the issue to more clearly show this.
My statement that this issue hasn't been addressed still stand.

**Comment by sasumner** [comment]
@klanderfri Agreed.

**Comment by xylographe** [comment]
I think, the behaviour is correct. For each unsaved (ever) buffer a _Save as_ dialogue is presented. Selecting _Cancel_ could mean, cancel saving this one only, or cancel the whole _Save All_ operation. NPP has to assume the first alternative, otherwise it would be impossible to save some buffers and skip others.

Because the _Save_ dialogue is not a custom control, you cannot add a _“Cancel All”_ button.

**Comment by sasumner** [comment]
Hmm.  Maybe the best option in this (somewhat rare) case is the "trick" to hold down the `Esc` key until all of the unsaved docs have been take through the process?  I can live with that.  I tried it with 7 unsaved files and it isn't the speediest process, but it does work.

**Comment by xylographe** [comment]
Possible “solutions”:
1. If snapshots are enabled, save snapshot buffers to there backup location, or just skip them (they will be saved every X seconds anyway).
2. Add an option in Preferences to exclude snapshot buffers from _Save All_.

In both cases the user will have to explicitly select _Save_ or _Save as_ to make a snapshot buffer permanent.

**Comment by sasumner** [comment]
@xylographe Sounds like too much work. :-)

**Comment by klanderfri** [comment]
Another possible solution:
Having a dialogue asking "You have 10 unsaved documents. Do you want to run 'Save As' for all of them? - Yes/Cancel All
:-)

**Comment by xylographe** [comment]
@klanderfri Impractical, IMO.

**Comment by sasumner** [comment]
Agree with @xylographe

**Comment by donho** [comment]
Unfortunately, save dialog comes from system, on which I can do nothing about it.
So the enhancement cannot be done for this issue.

**Comment by klanderfri** [comment]
![image](https://user-images.githubusercontent.com/25903995/153671977-a341e805-2362-4e74-a6fc-650c68930551.png)
Thanks! Precisely what I needed! :-D

**Comment by klanderfri** [comment]
@donho, out of curiosity (and a pinch of bitterness for the sake of honesty and transparency): How come this enhancement was possible to implement now and not two years earlier? What did change? :-)

**Comment by klanderfri** [comment]
> > How come this enhancement was possible to implement now and impossible two years earlier? What did change? :-)
> 
> I think someone came, decided to contribute and provided a PR for that.

The best kind of fix. Thanks to that person! ^^
