### ISSUE TITLE
DSpellCheck.dll plugin causes crash when trying to print on Windows 10

### ISSUE THREAD

**Issue by byrnespd** [notepad-plus-plus/notepad-plus-plus#3968]
### Description of the Issue
Notepad++ 7.5.2 crashes anytime I try to print

### Steps to Reproduce the Issue
1. Open Notepad++ 
2. Try to print
3. Crash

### Expected Behavior
I expected the program to give me a list of printers to choose from

### Actual Behavior
It crashes

### Debug Information

**** The following is the current debug info - I removed DSpellCheck.dll 
**** Because doing so fixed the problem
Notepad++ v7.5.2   (32-bit)
Build time : Nov 27 2017 - 00:13:16
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : mimeTools.dll NppConverter.dll NppExport.dll 

Again, I removed DSpellCheck.dll from the plugins directory and reloaded NotePad++. I was able to print without any problem. From online searches, seems this plugin is a bit of a bug nuisance.

**Comment by dail8859** [comment]
@Predelnik

**Comment by Predelnik** [comment]
I wasn't able to reproduce it.
If you can download 1.3.3 version of plugin and send me a crash dump (right click in task manager and " Create Dump File") that would be tremendous help.
https://github.com/Predelnik/DSpellCheck/releases/download/v1.3.3/DSpellCheck_x86.zip

**Comment by SinghRajenM** [comment]
Could not reproduce, I tried with both "Foxit reader print PDF printer" and "Microsoft Print to PDF" queues. No issue, pdf has been created successfully.

**Comment by dail8859** [comment]
Can't reproduce it either. Tried v7.5.3 32-bit, both installed and stand alone, and tried DSpellCheck v1.3.2 and 1.3.3 on each one and no luck.

**Comment by yafa4me** [comment]
I'm seeing this as well - v7.5.3 (64 bit).  As byrnespd described, removing dspellcheck.dll allows eliminates the crash and allows printing as normal.

**Comment by Predelnik** [comment]
@byrnespd I ask you for the same favor then: can you download https://github.com/Predelnik/DSpellCheck/releases/download/v1.3.3/DSpellCheck_x64.zip and send me crash dump. That would be tremendous help.

**Comment by Predelnik** [comment]
I have possible suspicion that maybe it's due to missing `%appdata%/notepad++/plugins/config` directory. When there was plugin manager it was always created by it so there weren't any problem, but it also is created on Notepad++ install, so normally it should be there. I fixed in 1.3.3 but maybe underestimated importance of that problem.

**Comment by yafa4me** [comment]
It still crashed with v1.3.3.  The crash dump is about 45MB when zipped - though I'm not really sure if I created it correctly.  It won't upload though.

**Comment by Predelnik** [comment]
@yafa4me Thank you for helping! That seems to be correct size. Can you put it on something like dropbox/google drive/one drive? Maybe directly though email (mine is predelnik@gmail.com)

**Comment by yafa4me** [comment]
OK, it would email directly.  So, you should receive a message with a link to download the dump.

**Comment by Predelnik** [comment]
@yafa4me Thanks! I received a link, the data left me a bit confounded though, it seems like there is no indication of crash or presence of DSpellCheck.dll anywhere in call stack. Are you sure you captured it after Notepad++ crashed?

By the way just to make sure does clicking on spell-check icon/ pressing alt+a also crashes N++ for you or only calling print?

**Comment by yafa4me** [comment]
Yes, clicking on either the icon or using altA results in the program crashing.  I'll try the capture again.

**Comment by Predelnik** [comment]
@yafa4me Sorry to bother you once more and I'm really greatful for your cooperation, DSpellCheck now is correctly in call stack. but sadly the bit about using 1.3.3 version for reproducing crash was important. Since that version is the first one I attached debug info too, I've tried to figure out what's going on from assembly for a bit but it's really not that easy. So if it won't bother you could you please also send dump obtained with version 1.3.3.

**Comment by yafa4me** [comment]
Sorry, I had to use a different PC for the second dump and totally forgot about updating the file.  I won't be back in the office until Monday, but I'll try it again then.

**Comment by Predelnik** [comment]
@yafa4me No worries! Thank you for your trouble! I will try to scrape info from your dump and maybe other people will provide crash dumps also. So hopefully it will already be fixed by then :)

**Comment by Predelnik** [comment]
So for now what I came up with is that repeating the crash caused by renaming `plugins/config` directory on my side gives exactly the same callstack as provided by @yafa4me. Note equality in last 4 digits because DLL base address is multiple of 0x10000. It's hard to be a coincidence.
Missing `plugins/config`:
>	DSpellCheck.dll!00007ffe003a9cf3()	Unknown	No symbols loaded.
 	DSpellCheck.dll!00007ffe003a9c8a()	Unknown	No symbols loaded.
 	DSpellCheck.dll!00007ffe003a9ca5()	Unknown	No symbols loaded.
 	DSpellCheck.dll!00007ffe003affda()	Unknown	No symbols loaded.
 	DSpellCheck.dll!00007ffe0033b6ae()	Unknown	No symbols loaded.
 	DSpellCheck.dll!00007ffe00339ebf()	Unknown	No symbols loaded.
 	DSpellCheck.dll!00007ffe00316bce()	Unknown	No symbols loaded.

Crash Report:
> 	DSpellCheck.dll!00007ffe51579cf3()	Unknown	No symbols loaded.
 	DSpellCheck.dll!00007ffe51579c8a()	Unknown	No symbols loaded.
 	DSpellCheck.dll!00007ffe51579ca5()	Unknown	No symbols loaded.
 	DSpellCheck.dll!00007ffe5157ffda()	Unknown	No symbols loaded.
 	DSpellCheck.dll!00007ffe5150b6ae()	Unknown	No symbols loaded.
	DSpellCheck.dll!00007ffe51509ebf()	Unknown	No symbols loaded.
 	DSpellCheck.dll!00007ffe514e6bce()	Unknown	No symbols loaded.

However that's a bit contradictive because 1.3.3 clearly fixes the issue on my side. Anyway for anyone experiencing this issue, please check that you have `%appdata%/notepad++/plugins/config` in place. And in any case download 1.3.3 version, if you're still experiencing crash with it please provide a crash dump if possible.

**Comment by yafa4me** [comment]
Well, I think I've found a problem with the changes I made last week.  Instead of deleting the original dll file, I renamed it - assuming that a particular name was needed for it to load.  Today when I did the testing, I removed the old dll file and added the new version.  Doing this, indeed appears to fix the crash issue!

**Comment by Predelnik** [comment]
@yafa4me Thank you very much for testing and reporting results back!

@donho It looks like DSpellCheck 1.3.3 is better be provided with next version of Notepad++. This issue should be relatively rare since the required directories should generally be created on install but I can't be sure. Sorry for inconvenience.

**Comment by dail8859** [comment]
@Predelnik So is this issue considered fixed?

**Comment by Predelnik** [comment]
@dail8859 Yes with Notepad++ 7.5.4 which includes DSpellCheck 1.3.5 it's fixed.

**Comment by dail8859** [comment]
@Predelnik Thanks for the info! Closing.
