### ISSUE TITLE
AutoUpdate in x64 version downloads 32 bit installer

### ISSUE THREAD

**Issue by Chrischmi** [notepad-plus-plus/notepad-plus-plus#4090]
### Description of the Issue
I do have Notepad++ x64 installed. When it wants to auto-update, it downloads the 32 bit installer. The installer asks me to remove x64 to install 32 bit version.

### Steps to Reproduce the Issue
Auto-Update in x64

### Expected Behavior
x64 should stay x64

**Comment by SinghRajenM** [comment]
Please provide debug info (From menu -> ? -> Debug Info)

**Comment by Chrischmi** [comment]
After downloading x64 manually, I got the question to upgrade from 32 bit to x64. I guess, I read the message in the auto-upgrade wrongly - it tried to install x64, but I had 32 bit. Meanwhile, I have upgraded manually to x64. That's why the current debug info might not help at all anymore.

Notepad++ v7.5.4   (64-bit)
Build time : Jan  1 2018 - 01:50:29
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll

**Comment by GitMensch** [comment]
> I got the question to upgrade from 32 bit to x64. I guess, I read the message in the auto-upgrade wrongly - it tried to install x64, but I had 32 bit

If I understand this correctly the issue should be renamed to "auto-updater downloads 64-bit installer on 64-bit OS despite of 32-bit NPP".

But I cannot reproduce the issue, just did an auto-update of my NPP installation, result:

~~~
Notepad++ v7.5.4   (32-bit)
Build time : Jan  1 2018 - 01:47:45
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
~~~

Do you know which version you've tried to auto-update?

**Comment by Ynhockey** [comment]
I got the original issue as well, i.e. 64-bit Notepad++ asks to install 32-bit (which it did). Unfortunately I have already installed the new version and cannot reproduce the issue again at this time. I will try to manually install 64-bit again and see what happens on the next update.

**Comment by SinghRajenM** [comment]
@Ynhockey Do you know which version you were using earlier?

**Comment by Ynhockey** [comment]
@SinghRajenM Unfortunately I can't say for sure, but it was definitely 7.5.x

**Comment by Siedlerchr** [comment]
I can confirm this, I have installed 7.5.6 64 bit installed and then after a while I got an update notification, and it would offer me the same version 7.5.6 in 32 bit.  But when I manually trigger an update in the help menu, it says I am using the latest version,

```
Notepad++ v7.5.6   (64-bit)
Build time : Mar 19 2018 - 00:23:17
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll 
```

**Comment by ZeroCool940711** [comment]
Guys, I know its been a while since the last comment on this issue but I am having this problem too, I installed Notepadd++ 64 bit and then I got a notification to update, it installed a 32 bit version of notepad++ and now I also get the same update notification every time I open notepad++, its stuck in an endless update look.

**Comment by SinghRajenM** [comment]
@ZeroCool940711 
As this issue is consistently appearing for you. Could you please attached screenshot of task manager like below?
Please note: If you are not able to see the command line column, you can right click on "Name" or "PID" or any column header then click on "select columns" and choose "Command Line".

![image](https://user-images.githubusercontent.com/14791461/53286807-fd421080-3799-11e9-8b97-e4e61d78b9f0.png)

**Comment by MetaChuh** [comment]
@ZeroCool940711 

> its stuck in an endless update look.

if you were on 7.6.3 64 bit, the endless update loop of the same version has been fixed for now, as there was a typo in the submitted version number of a 7.6.3 install (version string 7.6.3 instead of 7.63).
so if you check for updates now, you won't see the same update again.

> I installed Notepadd++ 64 bit and then I got a notification to update, it installed a 32 bit version of notepad++

on the other hand the server sided updater fix mentioned above, does not solve the fact that at the next 7.6.4 update, you might see a 32 bit installer again, so look out for that, once 7.6.4 is out.

note: i have not been able to reproduce a 32 bit installer being downloaded by a 64 bit install, on clean machines, where no leftovers from an older 32 bit installation are hidden somewhere.
but all reported instances of this issue, where we got feedback over at the notepad++ community, have been able to be solved by uninstalling notepad++ completely **AND** deleting all older, eventually still existing notepad++ folders at the locations `%ProgramFiles%\Notepad++`, `%ProgramFiles(x86)%\Notepad++`, `%AppData%\Notepad++`, `%LocalAppData%\Notepad++`, and `%ProgramData%\Notepad++`, before installing notepad++ x64 again.

(yes it's much work, but it seems to have worked for the users that reported back, and you will also have an ultra clean install afterwards)

btw: if you are not a notepad++ community visitor yet, you are also very welcome to participate and share any of your experiences over at the notepad++ community forum: https://notepad-plus-plus.org/community/ to exchange any information with a wider audience of devs and regular users, that might have or need fixes and workarounds for many different issues.
(you don't have to sign up, just log in with your existing github or google account.)

**Comment by Faq** [comment]
Reading all this, not clear this happens bec of undeleted files or just leftovers in registry. If anyone could just write exact repo steps how to get this issue, would be easier to fix.
Never had such issue.

**Comment by MetaChuh** [comment]
not reproducible and no further community reports for incidents downloading a 32 bit installer for a 64 bit installation.

many thanks and best regards.

**Comment by N190392** [comment]
Hi.
I've had this problem for a long time, finally decided to search for solution. Problem is still there.

> Notepad++ v7.7.1   (64-bit)
> Build time : Jun 16 2019 - 21:24:47
> Path : C:\Program Files\Notepad++\notepad++.exe
> Admin mode : OFF
> Local Conf mode : OFF
> OS : Windows 10 (64-bit)
> Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll 

[https://i.imgur.com/4I5TRQ4.png](Image of 32bit being offered)

**Comment by GitMensch** [comment]
Somehow the following community response, provided by @N19392 got into my mail box but not here:

> Hi.
> I've had this problem for a long time, finally decided to search for solution. Problem is still there.

    Notepad++ v7.7.1 (64-bit)
    Build time : Jun 16 2019 - 21:24:47
    Path : C:\Program Files\Notepad++\notepad++.exe
    Admin mode : OFF
    Local Conf mode : OFF
    OS : Windows 10 (64-bit)
    Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll

[Image of 32bit being offered](https://i.imgur.com/4I5TRQ4.png)

**Comment by GitMensch** [comment]
@N19392 - can you please post a screenshot from the taskmanager as [requested above](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/4090#issuecomment-466647244)?

**Comment by lufog** [comment]
I have the same issue. I installed ```Notepad++ 7.9.2 64-bit``` and auto updater installed ```Notepad++ 7.9.3 32-bit```. As a result, in the "Programs and features", the old ```7.9.2 64-bit``` version remained and a new ```7.9.3 32-bit``` version appeared.
