### ISSUE TITLE
"Synchronize ... Scrolling" is disabled on launch with both views shown

### ISSUE THREAD

**Issue by Predelnik** [notepad-plus-plus/notepad-plus-plus#5250]
### Description of the Issue
In view menu - "Synchronize Vertical Scrolling" / "Synchronize Horizontal Scrolling" items - disabled when opening Notepad++ with both views shown.

### Steps to Reproduce the Issue

1. Open N++ with several documents
2. Transfer one of the documens to other view. In this moment `Synchronize...` items are enabled.
3. Close and open N++ again, `Synchronize...` items are disabled.

### Expected Behavior
`View->Synchronize...` items are enabled.

### Actual Behavior
`View->Synchronize...` items are disabled.

I can see that code for enabling/disabling these items initially is called but it seems to does not work correctly for some reason.

Notepad++ v7.5.9   (64-bit)
Build time : Oct 14 2018 - 15:19:55
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 8.1 (64-bit)
Plugins : mimeTools.dll DSpellCheck.dll NppConverter.dll PluginManager.dll

**Comment by pennygab** [comment]
Any news on that issue ? It's really annoying to always have to activate ... It was automatically activated in earlier versions of Notepad++

**Comment by R-Adrian** [comment]
i just hit this bug too...
i sometimes use the Compare plugin for Notepad++ to view side-by-side differences between two files and i was used to the syncronized scrolling being enabled automatically when comparing files.

Scrolling doesn't work automatically anymore and i have to enable it manually each time i use the Compare plugin. :(
https://github.com/jsleroy/compare-plugin/issues/99

**Comment by ds2000** [comment]
Same here, I've huge yaml and manifests to compare.  Only started since latest version was installed.

**Comment by mcvendrell** [comment]
Same bug here. Win 10, Notepadd++ v7.7 64 bits

**Comment by x33st0rm** [comment]
Just moved to Win10 from Win7, and this started happening to me too.
Same installation, same config.

Doesn't remember it being ticked on once i leave side-by-side view in Compare.

**Comment by MrTobyDog** [comment]
Slightly different (I think) - when I am comparing the two Synchronise menu items are greyed out but Horizontal is ticked - even though it is vertical I need

**Comment by xylographe** [comment]
Perhaps problems with ComparePlugin are due to PluginAdmin not installing the correct version?
Try updating ComparePlugin manually from [Compare releases](https://github.com/pnedev/compare-plugin/releases).

**Comment by MrTobyDog** [comment]
I installed the old version manually on 7.7.0 and is better - although enable horizontal by default not vertical! Anyway, got the job done!

**Comment by bradis1** [comment]
Win10, npp v7.7.1, using Compare plugin v2.0.0.0 nearly daily for XML/code files, noticed it stopped (automatically) sync'ing vertical scrolling sometime in the last few months. Could be tied to recent npp v7.7+ as hypothesized above.

Was able to manually set Vertical Sync Scrolling via View > Sync Vertical Scrolling... 
However, it does NOT seem to remain enabled.

Reproduce: setup compare of two files in own window (multi-instance mode), observe no sync'd vertical scroll. Enable View > Sync Vertical Scrolling. observe sync'd Vscroll. Clear Active Compare (ctrl+alt+x), then Compare (ctrl+alt+c). observe no sync Vscroll; in View menu the check for Sync vScroll has been cleared.

**Comment by dtwaling** [comment]
I am using notepad++ for comparing test code on a few different dev machines, and on two of them the work-around trick noted by @bradis1 worked great (a little extra to do, but gets the job done!).
However, for any other machines there has been NO work-around, and now it has even failed on the other two machines as well.  This it is becoming a drag since many of the files I need to compare are very long.

The OS in each case is Server 2016 or Win10 Ent/Pro (builds vary).  On the latest machine it failed on was working earlier today, I uninstalled the "Task List" plugin, npp restarted and then v-scroll sync now fails - below is the info I grabbed from help/"Debug Info..."  (note: info states Win 10, but this one is Server 2016)

Notepad++ v7.7.1   (64-bit)
Build time : Jun 16 2019 - 21:24:47
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : ComparePlugin.dll CSScriptNpp.dll CsvQuery.dll DSpellCheck.dll jN.dll JSMinNPP.dll mimeTools.dll NppConverter.dll NppEventExec.dll NppExec.dll NppExport.dll NPPJSONViewer.dll NppPluginDemo.dll NppPluginTemplate.dll NppRegExTractorPlugin.dll NppSaveAsAdmin.dll NppToolBucket.dll XMLTools.dll

**Comment by mcvendrell** [comment]
> > Perhaps problems with ComparePlugin are due to PluginAdmin not installing the correct version?
> > Try updating ComparePlugin manually from [Compare releases](https://github.com/pnedev/compare-plugin/releases).
> 
> I've just uninstalled and installed again by Plugin Manager and it worked for me. Thx

Didn't work for me. Still not vertical sync

**Comment by Stefan1200-de** [comment]
> EDIT: It works!! I supposed didn't work because the option "Vertical Sync" is not enabled, but it is working.
> So the solution in my case was update manually the ComparePlugin

Thanks, same helped here. Still unchecked, but it do synchronized vertical scrolling now.

**Comment by pnedev** [comment]
Hello all,

Just as an info - Compare plugin **does not** rely on Notepad++ vertical scroll sync setting.
The plugin actually turns Notepad++'s vertical scrolling **off** and while in compare does the vertical scrolling itself. After the compare the Notepad++ vertical scroll setting is restored.

The problems are due to the fact that since Notepad++ v7.7 (included) the plugins API is changed which makes the old plugins (the ones that are not rebuild with the new N++ API) prone to all kinds of errors. So you'll need to reinstall the correct version of Compare plugin for Notepad++ versions above 7.7. You can do that manually or through the PluginsAdmin feature.
I would suggest doing that for **all your plugins** as well.

Read more here: https://github.com/pnedev/compare-plugin/issues/201

**Comment by BNGI** [comment]
I opened a new point #8635. Maybe it's the same issue described here, although in my case having ComparePlugin or not doesn't make a difference. But it seems that the issue of not being able to activate synchronized scrolling is there and easy to overcome by simply moving a file from the left pane to the right or vice versa.

**Comment by guidobbb** [comment]
I had the same issue!
Just upgraded Compare from v2 to v2.0.1 and it's solved!
Vertical scrolling is now set to default within the plugin, without having to use the option under View\Synchronize Vertical Scrolling.

**Comment by donho** [comment]
So according @guidobbb 's report, it's rather a plugin issue and it's fixed in concerning plugin (Compare plugin v2.0.1).

**Comment by sasumner** [comment]
STR on 7.9.2:

Start with one file, then clone it into the other view:

![image](https://user-images.githubusercontent.com/30118311/107644823-f2fad480-6c45-11eb-9f32-3ec4da65a500.png)

Drop the _View_ menu, observe:

![image](https://user-images.githubusercontent.com/30118311/107644907-0c038580-6c46-11eb-8731-b08390cb1d10.png)

Restart N++, file is reopened into both views (as before).

Drop the _View_ menu, observe:

![image](https://user-images.githubusercontent.com/30118311/107645106-4a00a980-6c46-11eb-8c79-5193ffda8085.png)

At this point the synchronization items should be enabled, but they are not.

Notepad++ v7.9.2   (64-bit)
Build time : Dec 31 2020 - 04:01:34
Path : C:\.............\npp.7.9.2.portable.x64\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1909
OS Build : 18363.1316
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by BNGI** [comment]
Don,

That's why I opened #8635 some time ago, because I realized that having or not Compare plugin (mentioned in this thread) actually didn't make any difference; I think mentioning the Plugin in this thread made the whole thing to seem a plugin-related issue, while it's not. I can't recall exactly when this issue started, but it may have been more than one year ago.

**Comment by daniloz** [comment]
👍

**Comment by alankilborn** [comment]
Tested in N++ 8.4.4 (current version as of this writing) and problem still exists.

**Comment by sunbear87** [comment]
Same problem for me.

I don't use the Compare plugin and it's not installed.

**Comment by Topoti22** [comment]
it is still not resolved

**Comment by buggalicious** [comment]
it is still not resolved
a very bugging bug indeed

**Comment by alankilborn** [comment]
I notice on 8.4.9 at least, the two toolbar buttons for synchronization ARE enabled when Notepad++ starts up with 2 views, even though the two _View_ menu items are disabled in this situation.  So I suppose a workaround is to use the toolbar buttons to enable synch.

**Comment by pryrt** [comment]
@donho ,

Two years ago, you thought this was plugin related, based on other posters who had also mentioned a plugin (as a point of comparison, not as a description of the culprit).  But as was explained after your last post, it's not caused by any plugin.  This problem was replicated in 2021 using v7.9.2 with no additional plugins; and it can still be replicated in 2023 using a fresh v8.4.9.  The buggy behavior that was first described in v7.5.9 in 2019 still exists in v8.4.9 in 2023.

```
Notepad++ v8.4.9   (64-bit)
Build time : Jan 27 2023 - 03:11:16
Path : C:\usr\local\apps\npp\npp.8.4.9_fresh\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 20H2
OS Build : 19042.2486
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)
```

**Comment by alankilborn** [comment]
@donho @pryrt I can take a look into this one...

**Comment by donho** [comment]
@pryrt 
Thank you for pinging me.
There are too many opened issues and I cannot check them one by one...

@alankilborn 
Thank you for the PR.
I will check it ASAP.
