### ISSUE TITLE
Block Select (Alt-Shift) ONLY Using Numeric Keypad Automatically Replaces Selected Text with Garbage Characters

### ISSUE THREAD

**Issue by Metallisoft** [notepad-plus-plus/notepad-plus-plus#5321]
### Description of the Issue
When selecting text using Block Select (Alt+Shift) and the Numeric Keypad, releasing Alt+Shift immediately replaces the selected text with a single random ASCII character. I will get the letters r, A, d and also extended codes like 132, 150 and 192

This does not happen if I use the mouse, by clicking x1,y1, then holding Alt+Shift and clicking x2,y2.
This does not happen if I use the arrow keys.

This occurs in Win7, latest SP (2 desktops), and Win10, latest SP (one laptop).

### Steps to Reproduce the Issue

1. Position cursor at x1,y1
2. Hold Alt+Shift
3. Navigate to x2,y2 using the Numeric Keypad
4. Release Alt+Shift

### Expected Behavior

Selected block to remain highlighted and unchanged.

### Actual Behavior

Select block was replaced with a random ASCII character from 0-255

### Debug Information

Notepad++ v7.6.3   (32-bit)
Build time : Jan 27 2019 - 17:20:30
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll

**Comment by Metallisoft** [comment]
This issue is still present in v7.8.7

**Comment by sasumner** [comment]
I do not see this in 7.8.9, but maybe I'm just not doing it the same way.
Please provide a specific example that replicates it for you.  In other words, don't use x1,y1,x2,,y2.  Start with some sample text, tell where exactly the x1,y1 is, etc.

**Comment by Metallisoft** [comment]
Hi! Sure thing.

Sample text:

The quick fox jumped over the lazy dog
The quick fox jumped over the lazy dog
The quick fox jumped over the lazy dog
The quick fox jumped over the lazy dog

If you put your cursor on the first line, 5th column(the Q), then holding Shift-Alt, use the numeric keypad arrows to move down and to the right to the last line, 34th column (the Y). 

Releasing Shift-Alt immediately replaces the marked text with a random character. In this test, it looks like this:

The è dog
The è dog
The è dog
The è dog

If I use the mouse to select the block of text, or the regular arrow keys, releasing Shift-Alt does nothing, and leaves the text marked for my next action.

**Comment by sasumner** [comment]
Well, I can reproduce it with those instructions (on 7.8.9).  👍

**Comment by sasumner** [comment]
I'm not sure what to think about this one.
Some other editors that support block mode selection with Alt (VSCode, SciTE) also act this same way.
I could not make Visual Studio's text editor reproduce it, though.

I'd welcome other comments here, reporting on the behavior of other editors that support it.

Since SciTE reproduces it, I'll punt and label this as depending-on-Scintilla.

@Metallisoft , I presume there is a good reason you are using the column-select feature with the arrows shared on the numeric keypad?  Like for instance your computer has no dedicated arrow keys?

**Comment by r0polach** [comment]
Hi,
I am also affected with this issue, especially when I work on my laptop integrated keyboard
which has dedicated arrow keys very small and in very impractical position, so I use arrows
on the num-pad with num-lock off. I use column blocks often, and due this bug I switched
to Geany editor temporarily until this issue is resolved, as Geany has also column block feature
with very similar behavior to Notepad++ (but without this bug).

**Comment by sasumner** [comment]
Certainly one thing that could be done as a workaround at the user level is to reassign the keycombinations where `Alt` is involved.  Thus, go into the _Settings_ menu, choose _Shortcut Mapper..._ and reassign these to combinations that do not have `Alt` in the mix :

![image](https://user-images.githubusercontent.com/30118311/92240085-09785500-ee8a-11ea-9a0f-ef51764197a3.png)

So a suggestion might be to go with `Ctrl+Shift+` rather than `Alt+Shift+` for the four of these.

`Ctrl+Shift` + arrows are by default already assigned to other functions, but those could be reassigned as well, or removed if those functions aren't used by a particular user.

**Comment by sasumner** [comment]
>Geany has also column block feature with very similar behavior to Notepad++ (but without this bug).

Geany also uses Scintilla, so I'm curious as to how this doesn't happen with that editor, when it happens with Scintilla's own demo editor (SciTE).

**Comment by Metallisoft** [comment]
@sasumner

Thanks for the follow up!

The dedicated arrow keys are inferior to using the numeric keypad, as far as navigation of text. It's thrice faster to move through code with them than awkwardly transitioning from arrows to Home/End and such. I almost never use the numpad for numbers.

I've not seen this behavior in any other application to date that supports block select. It's is only within Notepad++ that this is an issue. 

Remapping to a non-standard configuration is not an acceptable workaround. I cannot spend house in one program onto have to alter my use in another.

**Comment by sasumner** [comment]
As I said earlier, this is going to be something Scintilla handles, not Notepad++.  In that light I did some searching and uncovered this from 2008:  https://sourceforge.net/p/scintilla/feature-requests/444/#4d5a which says, so you don't have to follow the link:

`Tried out the column selection mode using Alt+Shift keys. When I use it conjunction with the arrow keys in the numeric keypad, it appears to be buggy. In several cases it deleted what I was highlighted and inserted garbage before I could copy or cut the information. I tried the standard arrow keys and it appears to work fine. I usually use the numeric keypad for arrow navigation (with num lock off) and never touch the standard arrow keys though. Would be nice if both sets of arrow keys functioned the same way`

Perfect issue report about this -- am I right? :-)

The response from the Scintilla project folks at that time was:

`The behaviour noticed by ... is the standard use of the Alt key to allow typing characters by their numeric code - try holding down Alt while typing Keypad 5 twice and you should see '7' in most applications and the same occurs while holding Shift+Alt. Visual Studio exhibits similar behaviour but possibly only when Keypad 5 is used in the sequence. While its probable that Visual Studio could be emulated by detecting that a sequence of numeric keypad keys were hit and then ignoring the next character, it looks complex so I won't be working on this ...`

The issue was finally closed by Scintilla in 2010 with no further action.

**Comment by r0polach** [comment]
It seems that Geany is able to workaround this issue. Probably Scintilla
can configure this somehow?

Anyway, on the Scintilla side, it would be more convenient that Alt+numkey
usage for entering characters
by their numeric code would work only if the num lock is on.

**Comment by r0polach** [comment]
Personally, I do not prefer the workaround of remapping the Alt+... to Ctrl+ for column blocks,
because I switch between Windows and Linux often and I use Geany on Linux too.

**Comment by sasumner** [comment]
Further research:

From Scintilla [HISTORY](https://www.scintilla.org/ScintillaHistory.html) for version 4.3.1:

`On Win32, the numeric keypad with Alt pressed can be used to enter characters by number. This can produce unexpected results in non-numlock mode when function keys are assigned. Potentially problematic keys like Alt+KeypadUp are now ignored.` [Bug 1252](https://sourceforge.net/p/scintilla/bugs/2152/)

Too bad that older issue from 2008 was not linked to this new information--it would have made it easier to find.

Summary:  So the bottom line is that Notepad++ will obtain this fix when it goes to Scintilla 4.3.1 or later.  Current N++ (7.8.9) uses Scintilla 4.2.0.

**Comment by Metallisoft** [comment]
That is awesome! Thank you guys for the follow ups. I can't wait to tell everyone at the office tomorrow.

**Comment by sasumner** [comment]
@Metallisoft 

> I can't wait to tell everyone at the office tomorrow.

What are you going to tell them to get them all excited about?
That Notepad++ will get this feature at some indeterminate future date?  
Potentially a long time from now?

Do you mean to say that everyone "at the office" has the same awful computer keyboards?
That's sad.  :-)

**Comment by sasumner** [comment]
I build the Scintilla 4.44 source code appropriate for Notepad++ and tried this issue with that.
For a reason I don't yet understand, and maybe won't understand :-)
this issue was not resolved by doing that -- the same symptom exists.
So I give that a big :-(

**Comment by astrosofista** [comment]
> Releasing Shift-Alt immediately replaces the marked text with a random character.

Hi. Affected by the same issue, I found a simple solution, it works on my setup —Win7 & NPP 7.8.9— and I hope on yours as well. Please do the following: Instead of releasing both the shift and alt keys at the same time, first just release the shift key while holding alt; then press the shift key again and release alt, finally the shift key. That's all. Now the marked text is not replaced by any random character. HTH

**Comment by sasumner** [comment]
> Instead of releasing both the shift and alt keys at the same time, first just release the shift key while holding alt; then press the shift key again and release alt, finally the shift key

I haven't tried it to verify, but, isn't it a bit burdensome?
I'm all for workarounds, but...they have to be workable.  :-)

**Comment by astrosofista** [comment]
> I haven't tried it to verify, but, isn't it a bit burdensome?
> I'm all for workarounds, but...they have to be workable. :-)

Well, what can I say, I get used to it. There is another workaround to avoid the unwanted replacement, maybe a simpler one: the trick is to press, for example, the left arrow key and then the right one —in order to preserve the selected text—, while holding both the shift and alt keys. Then it is safe to release the last mentioned keys.

**Comment by sasumner** [comment]
@vinsworld I'm interested if you can judge this one solved or not with the Scintilla 4.4.6 integration...if you'd like to try it.

**Comment by Metallisoft** [comment]
I just upgraded to v7.9.1 (Nov 2020 build) today, and it displays the same behavior.

I was messing with this last month, and found it's not actually random; it's specific to what keys are used in what order. For example:

The quick fox jumped over the lazy dog
The quick fox jumped over the lazy dog
The quick fox jumped over the lazy dog

Placing the cursor at the beginning of the first row, Shift+Alt+626 always selects 2 columns, 2 rows, and generates a lowercase r.

re quick fox jumped over the lazy dog
re quick fox jumped over the lazy dog
The quick fox jumped over the lazy dog

Alt+626 also generates a lowercase r (without any selecting, just types the character). Lowercase r is ASCII 114, so not sure how that's getting mapped. Alt+114 generates a lowercase r as expected.

Shift+Alt+2666 selects 2 rows, three columns, and replaces with a lowercase j. Alt+2666 by itself also generates a lowercase j (no selection), as well as the actual ASCII value, Alt+106.

For whatever reason, N++ also changes the typed ASCII by just spamming the same number. The result of Alt+6, Alt+66, [...], Alt+6666666666, creates this string: ♠BÜ◙j*¬¬¬¬

In SQL Server 2014, Shift+Alt+2666 just selects the block text. Looks like Microsoft's solution is to check for Shit+Alt, and ignore the ASCII insert. Without Shift, Alt+266 and Alt+2666 and Alt+26666 all generate whatever this is: ◙

HTH

**Comment by sasumner** [comment]
>I just upgraded to v7.9.1 (Nov 2020 build) today, and it displays the same behavior.

Nothing has changed in a N++ release concerning Scintilla since we talked before on this, so nothing is surprising about 7.9.1 having the "same behavior".

There is the possibility that the next version of N++ (at this writing likely to be the 7.9.4 release) will solve it as it will contain a newer Scintilla that is reported to fix the problem.  But at this writing, it is an unknown.

**Comment by sasumner** [comment]
@Metallisoft So I just checked the current Notepad++/Scintilla build for this, following the instructions for "current build" here:  https://github.com/notepad-plus-plus/notepad-plus-plus/wiki/Testing

Then I tried the sample scenario with which I could reproduce this problem with before:
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5321#issuecomment-674092520

What I found was not only does it not work correctly in the current build, it is worse than the older test.
Testing before would allow me to column select the block and then corruption would occur when the keys were released.
With the current build, I can't select the block.

**Comment by ArkadiuszMichalski** [comment]
Strange, this still exist in case from opener [(for this shortcut](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5321#issuecomment-687119421)), but for this works fine:

![image](https://user-images.githubusercontent.com/2730894/109552228-cc57ed00-7ad1-11eb-9ad4-79b43fbfdf8b.png)

The fault is still on the side of Scintilla? If so, it is worth reporting. 

If someone really wants to use the numeric keypad with Alt, he has to remap the keys with some tool. 
https://superuser.com/questions/668394/how-to-turn-off-alt-numeric-keypad-ascii-symbol-insertion

Unfortunately, in Windows it is not possible to disable the insertion of characters by using Alt and the numeric keypad (instead there is a whole bunch of unnecessary things.).

**Comment by ArkadiuszMichalski** [comment]
@sasumner
I checked last SciTE (4.4.6) and this works fine for above Scintilla commands. Either this [fix has](https://sourceforge.net/p/scintilla/bugs/2152/) to be turned on somehow, or something on the NPP side is wrong.

**Comment by sasumner** [comment]
@ArkadiuszMichalski 
For me in SciTE 4.4.6 I get pretty much the same behavior I do in Notepad++ with Scintilla 4.4.6.
Meaning that in the "quick brown fox" scenario I can't get the column block to start forming.
I press either Shift+Alt+6 or Shift+Alt+2 and my caret won't leave the "q" in "quick".
Then when I let up on all the keys a single bogus character pops up right before the "q" in the first line.

**Comment by ArkadiuszMichalski** [comment]
@sasumner 

But what commands in SciTE did you assign to these shortcuts? In `SciTEGlobal.properties` file I add:
```
# User defined key commands
user.shortcuts=\
Ctrl+Shift+V|IDM_PASTEANDDOWN|\
Ctrl+PageUp|IDM_PREVFILE|\
Alt+Up|SCI_LINEUPRECTEXTEND|\
Alt+Down|SCI_LINEDOWNRECTEXTEND|\
Alt+Right|SCI_CHARRIGHTRECTEXTEND|\
Ctrl+PageDown|IDM_NEXTFILE|
```

and shortcuts with Alt works also in numpad.

**Comment by sasumner** [comment]
>what commands in SciTE did you assign to these shortcuts?

Why would I assign anything?
In SciTE, Shift+Alt+arrows (the dedicated arrows) work to create a column block.
Are you saying I have to assign like you show in order to see Shift+alt+numpadarrows successfully create a column block?

**Comment by sasumner** [comment]
@vinsworldcom I'm surprised that you didn't weigh in on this one, after I gave you a little prod [HERE](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5321#issuecomment-783357742).  It really would be nice to have another opinion here.

**Comment by vinsworldcom** [comment]
@sasumner just saw this comment.  The one you referred to has me @-mentioned as `@vinsworld`, not `@vinsworldcom` so I never saw it.  I'll check now; sorry for the delay.

Cheers.

**Comment by ArkadiuszMichalski** [comment]
@sasumner 
>Why would I assign anything?

Because this is probably how it was fixed, only assigning shortcuts changes the default behavior of numpad.  But I might be wrong, check by yourself  the Scintilla bug discussion.

**Comment by sasumner** [comment]
It appears that this issue might be a "comedy of errors" and misinterpretations on my part.  :-(

Back [HERE](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5321#issuecomment-688272711) I indicated that Scintilla had fixed the problem, but reading it again (and with @ArkadiuszMichalski 's post above freshening it for me):

`On Win32, the numeric keypad with Alt pressed can be used to enter characters by number. This can produce unexpected results in non-numlock mode when function keys are assigned so potentially problematic keys are ignored.`

I _NOW_ read this as Scintilla has decided that it will not attempt to handle Alt (which includes mainly Shift+Alt for our concerns here) when used in conjunction with arrows on the numeric keypad, it will simply ignore these presses.

And indeed, that is what I'm seeing with SciTE446 and Notepad++ with SciLexer446:  Shift+alt+keypadarrows don't navigate to define a column block.  Additionally, after attempting these types of movements, when I release all keys, I get a single "garbage character" inserted at the caret point.

**Comment by vinsworldcom** [comment]
> I do in Notepad++ with Scintilla 4.4.6.
> Meaning that in the "quick brown fox" scenario I can't get the column block to start forming.
> I press either Shift+Alt+6 or Shift+Alt+2 and my caret won't leave the "q" in "quick".
> Then when I let up on all the keys a single bogus character pops up right before the "q" in the first line.

This is the same behavior I get with 7.9.3/4.4.6.  I also get the previously mentioned block turns to lower case "r" using 7.9.3/4.2.0.

> And indeed, that is what I'm seeing with SciTE446 and Notepad++ with SciLexer446: Shift+alt+keypadarrows don't navigate to > define a column block. Additionally, after attempting these types of movements, when I release all keys, I get a single "garbage > character" inserted at the caret point.

I think what we're seeing is the Alt+NUMBER = character code insertion?  For me `Alt+62` thinking should be right, then down, actually inserts `>` which is the ASCII code 62.

Cheers.

**Comment by ArkadiuszMichalski** [comment]
@sasumner 

 https://sourceforge.net/p/scintilla/bugs/2152/#efff/effb
>...is it intentional? In this way we can somehow "deactivate" windows' insertion mode...

>Neil Hodgson - 20 hours ago 
>There was no intention here of denying the Windows character entry behaviour. Its just a side effect because user.shortcuts is implemented in the event loop of the application (SciTE) to drop out of processing keys early and not call TranslateAccelerator / TranslateMessage / DispatchMessage. The event loop is application code and Scintilla can not usurp this.

**Comment by sasumner** [comment]
@ArkadiuszMichalski Sorry, I still don't see what could be done on the Notepad++ side to make this work.  If you think you have an idea, and can be explicit about it, I'm certainly willing to give it a try.
