### ISSUE TITLE
Closing dialog shows disabled buttons [regression]

### ISSUE THREAD

**Issue by jbaker6953** [notepad-plus-plus/notepad-plus-plus#7782]
### Description of the Issue
When closing Notepad++ the closing dialog shows irrelevant buttons "Yes to all" and "No to all."

### Steps to Reproduce the Issue
1. Open Notepad++ with only a single tab.
2. Type some text.
3. Close Notepad++

### Expected Behavior
The dialog appears as in versions 7.7.1 and prior.

### Actual Behavior
[Screen shot](https://i.imgur.com/7n5lXT4.png)

Suspect https://github.com/notepad-plus-plus/notepad-plus-plus/commit/4ebcf6191701963566ba575a65a11a56944570f9#diff-66cb37e830bebcbf71f3bfa2e91659c6

**Comment by sasumner** [comment]
I stand by MY original opinion (see #7563) that having the `Yes to all` and `No to all` buttons present but disabled (like shown in the screen shot) is fine and doesn't need to be changed.

The author of Notepad++ originally agreed with me, but later changed his mind and removed these buttons (see #7762 and see the commit mentioned there).

Regardless, this has already been "fixed". :-)

**Comment by xylographe** [comment]
Unfortunately, the "fix" made it worse. The dialogue without "to All" is not a custom control. Hence, the two Save dialogues may not use the same language, and have different accelerator keys for Yes and No.

**Comment by jbaker6953** [comment]
What was the origin of the change in 7.8 that made the disabled buttons visible? It seems like the best fix would address whatever issue that commit was trying to address AND avoid displaying unnecessary elements (if possible).

**Comment by sasumner** [comment]
>Unfortunately, the "fix" made it worse.

Ah, I was not aware of that!

**Comment by sasumner** [comment]
>What was the origin of the change in 7.8 that made the disabled buttons visible?

Not sure I understand the question.  There were only Yes/No/Cancel before.

**Comment by jbaker6953** [comment]
I was trying to figure out what problem was being addressed by the original change that made the disabled buttons visible.

**Comment by sasumner** [comment]
@jbaker6953 Say you have 100 changed files and you don't want to save any of them, but you want all of their tabs to be closed.  Instead of answering 100 individual prompts with "No", you just say "No to All".  Somehow I still don't think this is answering your question (because it seems really obvious).

**Comment by jbaker6953** [comment]
Sorry for the lack of clarity. I meant, in past versions, the dialog would only have "Yes" or "No" if there was one tab, but if there was more than one tab it would show "Yes to all" and "No to all" in addition. I'm trying to understand the intent behind showing "Yes to all" and "No to all" even when there's only one tab.

**Comment by sasumner** [comment]
@jbaker6953 I didn't implement the feature, but I think showing the "...to all" buttons is simply the easiest way to implement it.  Instead of making the buttons invisible (which would leave a lopsided looking dialog box, barring resizing it -- more work) they were just disabled.  Personally, I like it; it lets me know that there are various conditions in which those buttons (and, importantly, their features) will be made available.  I do understand the other side of it as well (that people might not like it).  But it seems that the "demand" for them not to be shown has created new problems (reference @xylographe 's comment above).

**Comment by jbaker6953** [comment]
I think I see the source of the confusion. What I'm seeing is the "Yes to all" and "No to all" even when I'm closing a specific tab (not all tabs and not the notepad++ program). There is never a case where closing one tab needs "Yes to all" or "No to all," so it's a bit disorienting.

It would be useful in the case of closing multiple tabs with changed files. I wonder if there's a way to size the dialog to just cut those buttons off when closing individual tabs or total open tabs == 1?

**Comment by sasumner** [comment]
@jbaker6953 Maybe the best advice for you is to wait for the next released version (after 7.8.2) which should be different in this regard, and if you have further comments after that, come back here and post them. :-)
