### ISSUE TITLE
Notepad++ not responding state when network file is disconnected

### ISSUE THREAD

**Issue by dmelnik92** [notepad-plus-plus/notepad-plus-plus#8055]
### Description of the Issue

Notepad++ not responding state when network file is opened and the network location is no longer available

### Steps to Reproduce the Issue

1. Open a network located file in notepad++
2. Disconnect the network drive or lose connectivity to the network location
3. Open notepad again or make the window active

### Expected Behavior

A notification that the network drive is no longer available. A faster response.

### Actual Behavior

Notepad++ went to not responding state.

**Comment by m0m4x** [comment]
This issue creates lots of suffering if you work lots on different enviroments.. Please Fix it...  Thank you!

**Comment by sukhoi191** [comment]
After quick analysis, Microsoft's `PathFileExists` defined in "Shlwapi.h" fails in this specific case. Program hangs on the first `PathFileExists` call in `Notepad_plus::loadSession`. This function is used in lots of places throughout the code. I guess changing it in a single place and leaving other calls intact is not a good idea, so fixing it would require modifying multiple files. I'll try to prepare a fix for this using a different method (maybe C++'s fstream?).

I will also try to create a simple project showcasing this issue and report a bug to Microsoft but I wouldn't hold much hope they'll do much about it.

**Comment by sukhoi191** [comment]
Here's an interesting finding: if I use `PathFileExistsW` or `PathFileExistsA` directly (even though `PathFileExists` is only a define which points to either one of these functions, depending on the Unicode setting), it works correctly. The question is, can we safely use `PathFileExistsW` (which is the Unicode version) at all times?

**Comment by soutzis** [comment]
Came here to open this exact issue. I can confirm that this is also happening for version 8.6.2. However, I have found a kind of workaround to this: 
1. Open a file located in a network share in npp.
2. Close npp.
3. Disconnect the network (to lose access to the share).
4. Try to open npp by opening a local file - it should freeze.
5. Now try to rename that file and npp will unfreeze. I did this 3 times, worked all 3 times.

However, if there could be some sort of "timeout" when opening inaccessible files, or if the function that checks if the file can be opened could be replaced with a different one that handles the error gracefully, then it would be very much appreciated.

**Comment by xomx** [comment]
possible workarounds:
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/12553#issuecomment-1747455487
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/12553#issuecomment-1888886357

@sukhoi191 
> we should use some other function, instead of PathFileExists?

I am wondering if a simple replacement by a WIN32 equivalent (e.g. GetFileAttributes, FindFirstFile, CreateFile ...) of that Windows shell SHLWAPI could help.

Personally, I am a bit skeptical that just that simple func swapping would work. Funcs like GetFileAttributes or PathFileExists are just synchronous, that's it. Even using of the asynchronous IO with the help of [CreateFile](https://learn.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-createfilew) & [FILE_FLAG_OVERLAPPED](https://learn.microsoft.com/en-us/windows/win32/devio/overlapped-operations) cannot help (you can then use asynchronous ReadFile/WriteFile WINAPI IO on the file handle created by such CreateFile, but the CreateFile call itself is still synchronous!)

I have no simple and clean solution here, sorry.
What could be doable is to write a N++ specific IsFile() func, in pseudo-code (as a possible PathFileExists replacement, it should have the same return type and input params):
```

BOOL PathFileExistsNpp(filename2test)
{
    if (IsThisANetworkFile(filename2test)) //  our func to be written
    {
        if (! IsThatNetworkFileResourceAlive-AsyncPingOrSimilar(filename2test)) //  our func to be written
            return FALSE;
    }
    
    return PathFileExists(filename2test); // standard WINAPI
}
```

**Comment by xomx** [comment]
I tried to write my own non-blocking cancellable IO variant of the PathFileExists to solve these networking timeout issues.
I put the work on hold due to lack of time and also did not have handy network storage to test the problem with.
I will see what I can do, but make no promises here...

**Comment by donho** [comment]
@xomx 
Is the function `bool Buffer::checkFileState()` which makes Notepad++ hanging?

**Comment by xomx** [comment]
@donho 
> Is the function `bool Buffer::checkFileState()` which makes Notepad++ hanging?
> (ie. GetFileAttributesEx doesn't respond when network not working)

I am still seeking for my own simple environment sln to reproduce these issues. But I think that your mentioned `GetFileAttributesEx` in the `Buffer::checkFileState()` may also be causing the described annoying UI response lag.

For a real N++ culprit detected, see the user [comment above](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8055#issuecomment-1131969608):
`After quick analysis, Microsoft's PathFileExists defined in "Shlwapi.h" fails in this specific case. Program hangs on the first PathFileExists call in Notepad_plus::loadSession. `

All of the possible affected WINAPIs in N++, like the user mentioned shell `PathFileExists` or your `GetFileAttributesEx`, ensure internally their functionality by calling down the `CreateFile` at the end. So I tried to write my own cancellable "CreateFileCancellabe" (that part I have already done, also my own "PathFileExistsCancellable" was not a problem). My idea is then replicate these network lags & debug all the places in N++ causing that. Then use my own cancellable replacements for these WINAPIs.

I will let you know if I make any progress.

**Comment by xomx** [comment]
@donho 

> Are you aware of this commit?
> [0858dfa](https://github.com/notepad-plus-plus/notepad-plus-plus/commit/0858dfa4afc4353653e9cf3fc47f8b23f18f48c2)

Yes. But I thought the `GetFileAttributesEx` would be just another way to use the synchronous `CreateFile` WINAPI internally. But when I poked around a bit in the Windows kernel now, I found out that it is something else, so maybe it can really help us with these non-responding problems caused by networks.

`GetFileAttributesEx` is implemented via `NtQueryFullAttributesFile`, which calls down the ntoskrnl I/O manager. At the end, it will all depend on how this final [call](https://github.com/reactos/reactos/blob/a7b111f5503e216bbcbb3c0070c2ff2fa112aa34/ntoskrnl/io/iomgr/file.c#L2404) will deal with any such problematic network state.

IMO - it is worth to try to ask the affected users here to re-test their issues with this new N++ way for checking the file status.

**Comment by donho** [comment]
@dmelnik92 @m0m4x @sukhoi191 @soutzis 

This issue might be fixed in Notepad++ v8.7:
https://community.notepad-plus-plus.org/topic/26105/notepad-v8-7-release-candidate

Could you guys try v8.7 and confirm the bug is fixed?

**Comment by soutzis** [comment]
> @dmelnik92 @m0m4x @sukhoi191 @soutzis 
> 
> This issue might be fixed in Notepad++ v8.7:
> https://community.notepad-plus-plus.org/topic/26105/notepad-v8-7-release-candidate
> 
> Could you guys try v8.7 and confirm the bug is fixed?

Will test tomorrow and let you know

**Comment by xomx** [comment]
@donho

If I am to believe this [post](https://stackoverflow.com/questions/1142080/how-to-avoid-network-stalls-in-getfileattributes), even with this WINAPI, the situation with possible network lag will not improve. But we will see what real user tests show us.

Under the above mentioned post, someone even mentions what I chose myself as a solution here - the [cancelable IO](https://stackoverflow.com/a/1142185).

**Comment by donho** [comment]
@xomx 
> If I am to believe this [post](https://stackoverflow.com/questions/1142080/how-to-avoid-network-stalls-in-getfileattributes), even with this GetFileAttributesEx WINAPI, the situation with the possible network lag will not improve. But we will see what real user tests show us.

Yes you might right - it seems the problem was shifted from FilePathExists to GetFileAttributesEx.
Let's wait & see the result of users' test on v8.7

**Comment by soutzis** [comment]
@donho @xomx 

Tested 5 times by opening a file on a remote SMB share and it seems that the issue is completely resolved. Takes about 5-10 seconds to open the rest of the local files and ignore the files on the share(s).

From my side, this seems to have been resolved.

**Comment by xomx** [comment]
Superb!
I hope that other users affected will have similar results.

**Comment by xomx** [comment]
@soutzis 

In your current test - did you also test the previously hanging version of the N++? (just for the comparison...)
Another user reported that v8.7rc does not fix his smb-issue: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/12553#issuecomment-2348761854

**Comment by soutzis** [comment]
> @soutzis 
> 
> In your current test - did you also test the previously hanging version of the N++? (just for the comparison...)
> Another user reported that v8.7rc does not fix his smb-issue: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/12553#issuecomment-2348761854
> 

No, I didn't test any known-affected version as I am not a local Administrator unfortunately. I've had this issue for 5+ years and now suddenly, I don't. It's hard to believe that it's a coincidence. 

If I have some time, I will try to recreate the issue on my personal computer this weekend and compare the behavior of both versions.

**Comment by donho** [comment]
@dmelnik92 @m0m4x @sukhoi191 @soutzis
Please check the fix (x64):
https://github.com/notepad-plus-plus/notepad-plus-plus/actions/runs/11079115559/artifacts/1989748610
There will be still few hanging time - but it's improved considerably.

**Comment by donho** [comment]
> I have no simple and clean solution here, sorry. What could be doable is to write a N++ specific IsFile() func, in pseudo-code (as a possible PathFileExists replacement, it should have the same return type and input params):
> 
> ```
> 
> BOOL PathFileExistsNpp(filename2test)
> {
>     if (IsThisANetworkFile(filename2test)) //  our func to be written
>     {
>         if (! IsThatNetworkFileResourceAlive-AsyncPingOrSimilar(filename2test)) //  our func to be written
>             return FALSE;
>     }
>     
>     return PathFileExists(filename2test); // standard WINAPI
> }
> ```

@xomx 
It is a good approach that I've been considering.
 However, `IsThisANetworkFile` function is not implemented easily because of mapping. And I have no idea how to do `AsyncPingOrSimilar`. 
 Finally, I have implemented the original idea in my mind: launching a thread with `GetFileAttributes` call and wait the call during 3 seconds, if the call is done during the 3 seconds we use the result of the call; otherwise we use the default value. It seems solve the hanging issue.
Your review is appreciated.

**Comment by donho** [comment]
Please try the latest state of fixed binary here (x64):
https://github.com/notepad-plus-plus/notepad-plus-plus/actions/runs/11118197845/artifacts/1998785683

The hanging issue should be improved considerably.

**Comment by soutzis** [comment]
> > @soutzis 
> > 
> > In your current test - did you also test the previously hanging version of the N++? (just for the comparison...)
> > Another user reported that v8.7rc does not fix his smb-issue: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/12553#issuecomment-2348761854
> > 
> 
> No, I didn't test any known-affected version as I am not a local Administrator unfortunately. I've had this issue for 5+ years and now suddenly, I don't. It's hard to believe that it's a coincidence. 
> 
> If I have some time, I will try to recreate the issue on my personal computer this weekend and compare the behavior of both versions. 
> 

Tested and validated. The fix works seamlessly for me.
